import Moveable from 'moveable';
import { readPsd, writePsd } from 'ag-psd';
import '../css/photoshop.css';

const state = {
    projects: new Map(), tabs: [], activeProjectId: null, activeLayerId: null, selectedLayerIds: new Set(),
    tool: 'move', zoom: 1, zooms: new Map(), selection: null, clipboard: null,
    moveable: null, panel: 'layers', histories: new Map(), imageElements: new Map(),
    dirtyProjects: new Set(), savedSignatures: new Map(), loadingFile: null,
    busy: false, nextProjectId: 1, nextLayerId: 1,
};

let documentTemplateCategories = [];
let activeTemplateCategory = 'social';
let selectedDocumentTemplateId = null;
const iconBase = '/ps-icons/';

const toolGroups = [
    {id:'move',key:'V',tools:[{id:'move',name:'Move Tool',icon:'tools-move'},{id:'artboard',name:'Artboard Tool',icon:'tools-artb'}]},
    {id:'marquee',key:'M',tools:[{id:'marquee',name:'Rectangular Marquee Tool',icon:'tools-rselect'},{id:'ellipse-marquee',name:'Elliptical Marquee Tool',icon:'tools-eselect'},{id:'single-row-marquee',name:'Single Row Marquee Tool',icon:'tools-sselect'}]},
    {id:'lasso',key:'L',tools:[{id:'lasso',name:'Lasso Tool',icon:'tools-lasso'},{id:'polygonal-lasso',name:'Polygonal Lasso Tool',icon:'tools-plasso'},{id:'magnetic-lasso',name:'Magnetic Lasso Tool',icon:'tools-mlasso'}]},
    {id:'selection',key:'W',tools:[{id:'object-selection',name:'Object Selection Tool',icon:'tools-oselect'},{id:'quick-selection',name:'Quick Selection Tool',icon:'tools-qselect'},{id:'magic-wand',name:'Magic Wand Tool',icon:'tools-mwand'}]},
    {id:'crop',key:'C',tools:[{id:'crop',name:'Crop Tool',icon:'tools-rcrop'},{id:'perspective-crop',name:'Perspective Crop Tool',icon:'tools-pcrop'},{id:'slice',name:'Slice Tool',icon:'tools-slice'}]},
    {id:'eyedropper',key:'I',tools:[{id:'eyedropper',name:'Eyedropper Tool',icon:'tools-eyedropper'},{id:'color-sampler',name:'Color Sampler Tool',icon:'tools-csamp'},{id:'ruler',name:'Ruler Tool',icon:'tools-ruler'}]},
    {id:'retouch',key:'J',tools:[{id:'spot-healing',name:'Spot Healing Brush Tool',icon:'tools-shbrush'},{id:'healing-brush',name:'Healing Brush Tool',icon:'tools-hbrush'},{id:'patch',name:'Patch Tool',icon:'tools-patch'},{id:'content-aware-move',name:'Content-Aware Move Tool',icon:'tools-mremove'},{id:'red-eye',name:'Red Eye Tool',icon:'tools-redeye'}]},
    {id:'brush',key:'B',tools:[{id:'brush',name:'Brush Tool',icon:'tools-brush'},{id:'pencil',name:'Pencil Tool',icon:'tools-pencil'},{id:'color-replacement',name:'Color Replacement Tool',icon:'tools-crepl'}]},
    {id:'clone',key:'S',tools:[{id:'clone-stamp',name:'Clone Stamp Tool',icon:'tools-clone'}]},
    {id:'eraser',key:'E',tools:[{id:'eraser',name:'Eraser Tool',icon:'tools-eraser'},{id:'background-eraser',name:'Background Eraser Tool',icon:'tools-beraser'},{id:'magic-eraser',name:'Magic Eraser Tool',icon:'tools-meraser'}]},
    {id:'fill',key:'G',tools:[{id:'gradient',name:'Gradient Tool',icon:'tools-gradient'},{id:'paint-bucket',name:'Paint Bucket Tool',icon:'tools-pbucket'}]},
    {id:'focus',key:'R',tools:[{id:'blur',name:'Blur Tool',icon:'tools-blur'},{id:'sharpen',name:'Sharpen Tool',icon:'tools-sharpen'},{id:'smudge',name:'Smudge Tool',icon:'tools-smudge'}]},
    {id:'tone',key:'O',tools:[{id:'dodge',name:'Dodge Tool',icon:'tools-dodge'},{id:'burn',name:'Burn Tool',icon:'tools-burn'},{id:'sponge',name:'Sponge Tool',icon:'tools-sponge'}]},
    {id:'pen',key:'P',tools:[{id:'pen',name:'Pen Tool',icon:'tools-pen'},{id:'freeform-pen',name:'Freeform Pen Tool',icon:'tools-fpen'},{id:'curvature-pen',name:'Curvature Pen Tool',icon:'tools-cpen'},{id:'add-anchor',name:'Add Anchor Point Tool',icon:'tools-aapoint'},{id:'delete-anchor',name:'Delete Anchor Point Tool',icon:'tools-dapoint'},{id:'convert-point',name:'Convert Point Tool',icon:'tools-capoint'}]},
    {id:'type',key:'T',tools:[{id:'horizontal-type',name:'Horizontal Type Tool',icon:'tools-htype'},{id:'vertical-type',name:'Vertical Type Tool',icon:'tools-vtype'}]},
    {id:'path',key:'A',tools:[{id:'path-selection',name:'Path Selection Tool',icon:'tools-pselect'},{id:'direct-selection',name:'Direct Selection Tool',icon:'tools-dselect'}]},
    {id:'shape',key:'U',tools:[{id:'rectangle',name:'Rectangle Tool',icon:'tools-rect'},{id:'ellipse',name:'Ellipse Tool',icon:'tools-ellipse'},{id:'polygon',name:'Polygon Tool',icon:'tools-pshape'},{id:'line',name:'Line Tool',icon:'tools-line'},{id:'custom-shape',name:'Custom Shape Tool',icon:'tools-cshape'}]},
    {id:'hand',key:'H',tools:[{id:'hand',name:'Hand Tool',icon:'tools-hand'},{id:'rotate-view',name:'Rotate View Tool',icon:'tools-rview'}]},
    {id:'zoom',key:'Z',tools:[{id:'zoom',name:'Zoom Tool',icon:'tools-zoom'},{id:'zoom-in',name:'Zoom In Tool',icon:'zoomIn'},{id:'zoom-out',name:'Zoom Out Tool',icon:'zoomOut'}]},
];

const actions = {
    newProject: () => document.getElementById('newProjectDialog').showModal(),
    openLocal: () => document.getElementById('localFileInput').click(),
    closeProject: () => closeTab(state.activeProjectId),
    saveProject: exportActiveProjectAsPsd,
    undo: () => restoreHistory(-1), redo: () => restoreHistory(1),
    exit: () => window.close(),
    selectAll: () => selectArea({x:0,y:0,width:activeProject()?.width||0,height:activeProject()?.height||0}),
    deselect: clearSelection, copy: copySelection, paste: () => pasteClipboard(false),
    pasteInPlace: () => pasteClipboard(true), newBlankLayer: createBlankLayer,
    addTextLayer: () => addTextLayerAtCenter(), duplicateLayer, renameLayer,
    restoreAspectRatio: restoreActiveLayerAspectRatio,
    zoomIn: () => setZoom(state.zoom*1.2), zoomOut: () => setZoom(state.zoom/1.2),
    fitScreen, actualPixels: () => setZoom(1),
    help: () => toast('Everything stays in this browser tab. Open a PSD or image, then use Save PSD to download your work.'),
};

function activeProject(){return state.projects.get(state.activeProjectId);}
function activeLayer(){return activeProject()?.layers.find(layer=>layer.id===state.activeLayerId);}
function selectedLayers(){const project=activeProject();if(!project)return [];const selected=project.layers.filter(layer=>state.selectedLayerIds.has(layer.id));return selected.length?selected:(activeLayer()?[activeLayer()]:[]);}
function selectOnlyLayer(id){state.activeLayerId=id||null;state.selectedLayerIds=new Set(id?[id]:[]);}
function selectLayerFromPanel(event,layer,ordered){if(event.shiftKey&&state.activeLayerId){const from=ordered.findIndex(item=>item.id===state.activeLayerId),to=ordered.findIndex(item=>item.id===layer.id);if(from>=0&&to>=0){state.selectedLayerIds=new Set(ordered.slice(Math.min(from,to),Math.max(from,to)+1).map(item=>item.id));state.activeLayerId=layer.id;return;}}if(event.ctrlKey||event.metaKey){if(state.selectedLayerIds.has(layer.id)){state.selectedLayerIds.delete(layer.id);if(state.activeLayerId===layer.id)state.activeLayerId=state.selectedLayerIds.values().next().value||null;}else{state.selectedLayerIds.add(layer.id);state.activeLayerId=layer.id;}return;}selectOnlyLayer(layer.id);}
function topLayer(project){return project?.layers.reduce((top,layer)=>!top||layer.z_index>top.z_index?layer:top,null);}
function nextProjectId(){return `document-${state.nextProjectId++}`;}
function nextLayerId(){return `layer-${state.nextLayerId++}`;}
function clonePlain(value){return value==null?value:JSON.parse(JSON.stringify(value));}
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML;}
function iconUrl(icon){return `${iconBase}${icon}.png`;}
function iconMarkup(icon,className='ps-icon',alt=''){return `<img class="${className}" src="${iconUrl(icon)}" alt="${escapeHtml(alt)}">`;}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3600);}
function setBusy(value){state.busy=value;updateSaveUi();}

function projectSnapshot(project){return {name:project.name,layers:project.layers.map(layer=>({...layer,textData:clonePlain(layer.textData)}))};}
function projectSignature(project){return JSON.stringify({name:project.name,layers:project.layers.map(({id,name,x,y,width,height,original_width,original_height,rotation,opacity,visible,z_index,type,text,blendMode})=>({id,name,x,y,width,height,original_width,original_height,rotation,opacity,visible,z_index,type,text,blendMode}))});}
function historyFor(project){if(!state.histories.has(project.id))state.histories.set(project.id,{entries:[],index:-1});return state.histories.get(project.id);}
function historyIcon(label){if(/move|align/i.test(label))return 'tools-move';if(/rotate/i.test(label))return 'rotate';if(/transform|resize|opacity|aspect/i.test(label))return 'tools-transform';if(/paste|layer|new|text/i.test(label))return 'lrs-newlayer';if(/open/i.test(label))return 'pix_layer';return 'panels-history';}
function initializeHistory(project,label,clean=false){state.histories.set(project.id,{entries:[{label,icon:historyIcon(label),snapshot:projectSnapshot(project)}],index:0});state.savedSignatures.set(project.id,clean?projectSignature(project):null);refreshDirty(project);}
function recordHistory(label){const project=activeProject();if(!project)return;const history=historyFor(project);if(history.index<history.entries.length-1)history.entries.splice(history.index+1);history.entries.push({label,icon:historyIcon(label),snapshot:projectSnapshot(project)});if(history.entries.length>100)history.entries.shift();history.index=history.entries.length-1;refreshDirty(project);renderHistory();}
function restoreHistoryTo(index){const project=activeProject();if(!project)return;const history=historyFor(project);if(index<0||index>=history.entries.length||index===history.index)return;history.index=index;const snapshot=history.entries[index].snapshot;project.name=snapshot.name;project.layers=snapshot.layers.map(layer=>({...layer,textData:clonePlain(layer.textData)}));state.selectedLayerIds=new Set([...state.selectedLayerIds].filter(id=>project.layers.some(layer=>layer.id===id)));if(!project.layers.some(layer=>layer.id===state.activeLayerId))selectOnlyLayer(topLayer(project)?.id||null);refreshDirty(project);render();}
function restoreHistory(direction){const project=activeProject();if(project)restoreHistoryTo(historyFor(project).index+direction);}
function refreshDirty(project){const dirty=projectSignature(project)!==state.savedSignatures.get(project.id);state.dirtyProjects[dirty?'add':'delete'](project.id);updateSaveUi();}
function updateSaveUi(){const project=activeProject(),status=document.getElementById('saveStatus'),button=document.getElementById('saveButton');if(!project){status.textContent='No document';button.hidden=true;return;}status.textContent=state.busy?'Working locally…':state.dirtyProjects.has(project.id)?'Unsaved changes':'Saved locally';button.hidden=!state.dirtyProjects.has(project.id);button.disabled=state.busy;}

function newLayer(project,{name='Layer',dataUrl,x=0,y=0,width,height,rotation=0,opacity=100,visible=true,z_index,type='pixel',text=null,textData=null,blendMode='normal'}){
    return {id:nextLayerId(),name,image_url:dataUrl,x:Number(x),y:Number(y),width:Number(width),height:Number(height),original_width:Number(width),original_height:Number(height),rotation:Number(rotation),opacity:Number(opacity),visible:Boolean(visible),z_index:z_index??project.layers.length,type,text,textData:clonePlain(textData),text_origin_x:Number(x),text_origin_y:Number(y),blendMode};
}

function createLocalProject({name,width,height,layers=[],historyLabel='New',clean=false}){
    const project={id:nextProjectId(),name,width:Number(width),height:Number(height),layers};
    state.projects.set(project.id,project);state.tabs.push(project.id);state.activeProjectId=project.id;selectOnlyLayer(topLayer(project)?.id||null);state.zooms.set(project.id,1);state.zoom=1;initializeHistory(project,historyLabel,clean);render();requestAnimationFrame(fitScreen);return project;
}

function canvasToDataUrl(canvas){return canvas.toDataURL('image/png');}
function transparentCanvas(width,height){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));return canvas;}
async function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Could not decode a local layer image.'));image.src=src;});}
async function imageFileToPng(file){const bitmap=await createImageBitmap(file);if(bitmap.width>8192||bitmap.height>8192){bitmap.close();throw new Error('Images are limited to 8192 × 8192 pixels.');}const canvas=transparentCanvas(bitmap.width,bitmap.height);canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();return {dataUrl:canvasToDataUrl(canvas),width:canvas.width,height:canvas.height};}

function countPsdLayers(children=[]){return children.reduce((count,layer)=>count+(layer.children?countPsdLayers(layer.children):1),0);}
function flattenPsdLayers(children=[],inheritedHidden=false,prefix=''){
    const result=[];
    for(const layer of children){const hidden=inheritedHidden||Boolean(layer.hidden);const name=prefix?`${prefix} / ${layer.name||'Layer'}`:(layer.name||'Layer');if(layer.children)result.push(...flattenPsdLayers(layer.children,hidden,name));else result.push({layer,hidden,name});}
    return result;
}
const cssBlendModes={normal:'normal',dissolve:'normal',darken:'darken',multiply:'multiply','color burn':'color-burn','linear burn':'multiply','darker color':'darken',lighten:'lighten',screen:'screen','color dodge':'color-dodge','linear dodge':'plus-lighter','lighter color':'lighten',overlay:'overlay','soft light':'soft-light','hard light':'hard-light','vivid light':'hard-light','linear light':'hard-light','pin light':'hard-light','hard mix':'hard-light',difference:'difference',exclusion:'exclusion',subtract:'difference',divide:'exclusion',hue:'hue',saturation:'saturation',color:'color',luminosity:'luminosity'};
function cssBlendMode(mode){return cssBlendModes[mode]||'normal';}
function canvasBlendMode(mode){const value=cssBlendMode(mode);return value==='plus-lighter'?'lighter':value;}
function colorCss(color){if(!color)return '#000000';const channel=value=>Math.max(0,Math.min(255,Math.round(Number(value)||0)));return `rgb(${channel(color.r)},${channel(color.g)},${channel(color.b)})`;}
function renderTextCanvas(textData){const text=String(textData?.text||'Text');const fontSize=Math.max(1,Number(textData?.style?.fontSize)||36);const lines=text.split(/\r?\n/);const probe=transparentCanvas(1,1),ctx=probe.getContext('2d');ctx.font=`${fontSize}px Arial`;const width=Math.max(2,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line||' ').width))+8));const lineHeight=Math.ceil(fontSize*1.25),height=Math.max(2,lineHeight*lines.length+6);const canvas=transparentCanvas(width,height),draw=canvas.getContext('2d');draw.font=`${fontSize}px Arial`;draw.textBaseline='top';draw.fillStyle=colorCss(textData?.style?.fillColor);lines.forEach((line,index)=>draw.fillText(line,4,3+index*lineHeight));return canvas;}

async function openPsdFile(file){
    const buffer=await file.arrayBuffer();
    const structure=readPsd(buffer,{skipLayerImageData:true,skipCompositeImageData:true,skipThumbnail:true});
    if(structure.width>8192||structure.height>8192)throw new Error('PSD documents are limited to 8192 × 8192 pixels.');
    if(countPsdLayers(structure.children)>500)throw new Error('PSD documents are limited to 500 layers.');
    const psd=readPsd(buffer,{skipThumbnail:true});
    const flattened=flattenPsdLayers(psd.children);
    const project={id:nextProjectId(),name:file.name.replace(/\.psd$/i,''),width:psd.width,height:psd.height,layers:[]};
    flattened.forEach(({layer,hidden,name},index)=>{
        const source=layer.canvas||('text' in layer?renderTextCanvas(layer.text):transparentCanvas(Math.max(1,(layer.right||1)-(layer.left||0)),Math.max(1,(layer.bottom||1)-(layer.top||0))));
        const x=Number(layer.left)||0,y=Number(layer.top)||0;
        const local=newLayer(project,{name,dataUrl:canvasToDataUrl(source),x,y,width:source.width,height:source.height,opacity:Math.round((layer.opacity??1)*100),visible:!hidden,z_index:index,type:layer.text?'text':'pixel',text:layer.text?.text||null,textData:layer.text||null,blendMode:layer.blendMode||'normal'});
        local.text_origin_x=x;local.text_origin_y=y;project.layers.push(local);
    });
    if(!project.layers.length&&psd.canvas){project.layers.push(newLayer(project,{name:'Background',dataUrl:canvasToDataUrl(psd.canvas),width:psd.canvas.width,height:psd.canvas.height,z_index:0}));}
    return createLocalProject({...project,historyLabel:'Open PSD',clean:true});
}

async function openRasterFile(file){const png=await imageFileToPng(file);const project={id:nextProjectId(),name:file.name.replace(/\.[^.]+$/,''),width:png.width,height:png.height,layers:[]};project.layers.push(newLayer(project,{name:file.name,dataUrl:png.dataUrl,width:png.width,height:png.height,z_index:0}));return createLocalProject({...project,historyLabel:'Open Image',clean:false});}
async function openLocalFile(file){state.loadingFile={name:file.name};switchPanel('layers');renderLayers();setBusy(true);try{return file.name.toLowerCase().endsWith('.psd')?await openPsdFile(file):await openRasterFile(file);}finally{state.loadingFile=null;setBusy(false);renderLayers();}}

async function layerCanvasForExport(layer){
    const image=await loadImage(layer.image_url),width=Math.max(1,Math.round(layer.width)),height=Math.max(1,Math.round(layer.height)),angle=Number(layer.rotation)||0;
    if(!angle){const canvas=transparentCanvas(width,height);canvas.getContext('2d').drawImage(image,0,0,width,height);return {canvas,left:Math.round(layer.x),top:Math.round(layer.y)};}
    const radians=angle*Math.PI/180,cos=Math.abs(Math.cos(radians)),sin=Math.abs(Math.sin(radians)),boxWidth=Math.max(1,Math.ceil(width*cos+height*sin)),boxHeight=Math.max(1,Math.ceil(width*sin+height*cos));
    const canvas=transparentCanvas(boxWidth,boxHeight),ctx=canvas.getContext('2d');ctx.translate(boxWidth/2,boxHeight/2);ctx.rotate(radians);ctx.drawImage(image,-width/2,-height/2,width,height);
    return {canvas,left:Math.round(layer.x-(boxWidth-width)/2),top:Math.round(layer.y-(boxHeight-height)/2)};
}
function exportTextData(layer){const text=clonePlain(layer.textData)||{text:layer.text||'Text',style:{font:{name:'ArialMT'},fontSize:36,fillColor:{r:0,g:0,b:0}}};text.text=layer.text||text.text||'Text';const transform=Array.isArray(text.transform)&&text.transform.length>=6?[...text.transform]:[1,0,0,1,layer.x,layer.y+(Number(text.style?.fontSize)||36)];transform[4]+=layer.x-(layer.text_origin_x??layer.x);transform[5]+=layer.y-(layer.text_origin_y??layer.y);text.transform=transform;return text;}
async function renderComposite(project){const canvas=transparentCanvas(project.width,project.height),ctx=canvas.getContext('2d');for(const layer of [...project.layers].sort((a,b)=>a.z_index-b.z_index)){if(!layer.visible)continue;const image=await loadImage(layer.image_url);ctx.save();ctx.globalAlpha=layer.opacity/100;ctx.globalCompositeOperation=canvasBlendMode(layer.blendMode);ctx.translate(layer.x+layer.width/2,layer.y+layer.height/2);ctx.rotate(layer.rotation*Math.PI/180);ctx.drawImage(image,-layer.width/2,-layer.height/2,layer.width,layer.height);ctx.restore();}return canvas;}
async function exportActiveProjectAsPsd(){
    const project=activeProject();if(!project||state.busy)return;setBusy(true);
    try{
        const children=[];
        for(const layer of [...project.layers].sort((a,b)=>b.z_index-a.z_index)){const rendered=await layerCanvasForExport(layer);const child={name:layer.name,left:rendered.left,top:rendered.top,canvas:rendered.canvas,opacity:layer.opacity/100,hidden:!layer.visible,blendMode:layer.blendMode||'normal'};if(layer.type==='text')child.text=exportTextData(layer);children.push(child);}
        const psd={width:project.width,height:project.height,children,canvas:await renderComposite(project)};
        const buffer=writePsd(psd,{generateThumbnail:true,invalidateTextLayers:true});
        const blob=new Blob([buffer],{type:'image/vnd.adobe.photoshop'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${project.name.replace(/[\\/:*?"<>|]+/g,'_')||'Untitled'}.psd`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
        state.savedSignatures.set(project.id,projectSignature(project));state.dirtyProjects.delete(project.id);updateSaveUi();toast(`Downloaded ${link.download}.`);
    }catch(error){toast(error.message||'Could not create the PSD file.');}finally{setBusy(false);}
}

function layerImage(layer,role){const key=`${role}:${layer.id}`;let image=state.imageElements.get(key);if(!image){image=new Image();image.draggable=false;state.imageElements.set(key,image);if(role==='canvas')image.addEventListener('pointerdown',()=>{if(state.tool==='move'&&document.getElementById('autoSelect').checked){selectOnlyLayer(image.dataset.layerId);renderLayers();renderProperties();updateMoveable();}});}image.className=role==='canvas'?'ps-canvas-layer':'ps-layer-thumb';image.dataset.layerId=layer.id;image.alt=layer.name;if(image.dataset.source!==layer.image_url){image.dataset.source=layer.image_url;image.src=layer.image_url;}return image;}
function render(){renderTabs();renderCanvas();renderLayers();if(state.panel==='properties')renderProperties();if(state.panel==='history')renderHistory();updateSaveUi();}
function renderTabs(){const tabs=document.getElementById('documentTabs');tabs.replaceChildren();state.tabs.forEach(id=>{const project=state.projects.get(id),tab=document.createElement('button');tab.type='button';tab.className=`ps-tab${id===state.activeProjectId?' active':''}`;tab.innerHTML=`<span class="ps-tab-name">${escapeHtml(project.name)}${state.dirtyProjects.has(id)?' *':''} @ ${Math.round((state.zooms.get(id)||1)*100)}% (RGB/8)</span><span class="ps-tab-close" aria-label="Close">${iconMarkup('cross')}</span>`;tab.addEventListener('click',event=>{if(event.target.closest('.ps-tab-close'))closeTab(id);else{state.activeProjectId=id;state.zoom=state.zooms.get(id)||1;selectOnlyLayer(topLayer(project)?.id||null);clearSelection();render();}});tabs.append(tab);});}
function renderCanvas(){state.moveable?.destroy();state.moveable=null;const project=activeProject(),canvas=document.getElementById('canvas'),shell=document.getElementById('canvasShell'),empty=document.getElementById('emptyState');canvas.querySelectorAll('.ps-canvas-layer').forEach(element=>element.remove());empty.hidden=!!project;shell.hidden=!project;if(!project)return;canvas.style.width=`${project.width*state.zoom}px`;canvas.style.height=`${project.height*state.zoom}px`;[...project.layers].sort((a,b)=>a.z_index-b.z_index).forEach(layer=>{const image=layerImage(layer,'canvas');Object.assign(image.style,{left:`${layer.x*state.zoom}px`,top:`${layer.y*state.zoom}px`,width:`${layer.width*state.zoom}px`,height:`${layer.height*state.zoom}px`,opacity:String(layer.opacity/100),display:layer.visible?'block':'none',zIndex:String(layer.z_index),mixBlendMode:cssBlendMode(layer.blendMode),transform:`rotate(${layer.rotation}deg)`});canvas.append(image);});renderSelection();requestAnimationFrame(updateMoveable);}
function syncLayerControls(){const layer=activeLayer(),blend=document.getElementById('layerBlendMode'),opacity=document.getElementById('layerOpacity'),slider=document.getElementById('layerOpacitySlider');blend.disabled=!layer;opacity.disabled=!layer;slider.disabled=!layer;if(layer){blend.value=layer.blendMode||'normal';opacity.value=layer.opacity;slider.value=layer.opacity;}}
function reorderLayer(draggedId,targetId,after){const project=activeProject();if(!project||draggedId===targetId)return;const ordered=[...project.layers].sort((a,b)=>b.z_index-a.z_index),from=ordered.findIndex(layer=>layer.id===draggedId);if(from<0)return;const [dragged]=ordered.splice(from,1);let target=ordered.findIndex(layer=>layer.id===targetId);if(target<0)return;if(after)target+=1;ordered.splice(target,0,dragged);ordered.forEach((layer,index)=>layer.z_index=ordered.length-1-index);if(!state.selectedLayerIds.has(dragged.id))selectOnlyLayer(dragged.id);else state.activeLayerId=dragged.id;recordHistory('Reorder Layers');render();}
function beginLayerRename(layer,label,row){const input=document.createElement('input');input.className='ps-layer-name-input';input.value=layer.name;label.replaceWith(input);row.draggable=false;input.focus();input.select();let finished=false;const finish=commit=>{if(finished)return;finished=true;const name=input.value.trim();if(commit&&name&&name!==layer.name){layer.name=name;recordHistory('Rename Layer');render();}else renderLayers();};input.addEventListener('click',event=>event.stopPropagation());input.addEventListener('dblclick',event=>event.stopPropagation());input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();finish(true);}if(event.key==='Escape'){event.preventDefault();finish(false);}});input.addEventListener('blur',()=>finish(true));}
function renderLayers(){
    const panel=document.getElementById('layersPanel'),project=activeProject();panel.replaceChildren();
    if(state.loadingFile){const row=document.createElement('div');row.className='ps-layer-row ps-layer-uploading';row.innerHTML=`<span></span><span class="ps-layer-spinner"></span><span class="ps-layer-name"><strong>${escapeHtml(state.loadingFile.name)}</strong><small>Opening locally…</small></span>`;panel.append(row);}
    if(!project){syncLayerControls();return;}
    const ordered=[...project.layers].sort((a,b)=>b.z_index-a.z_index);ordered.forEach(layer=>{
        const row=document.createElement('div');row.className=`ps-layer-row${state.selectedLayerIds.has(layer.id)?' selected':''}${layer.id===state.activeLayerId?' active':''}`;row.draggable=true;row.dataset.layerId=layer.id;
        row.innerHTML=`<button type="button" class="ps-layer-eye${layer.visible?'':' hidden-layer'}" title="${layer.visible?'Hide':'Show'} layer">${iconMarkup('lrs-eye')}</button><span class="ps-layer-name"><strong>${escapeHtml(layer.name)}</strong><small>${layer.type==='text'?'Text Layer':'Pixel Layer'}</small></span>`;
        row.insertBefore(layerImage(layer,'layers'),row.lastElementChild);
        row.querySelector('.ps-layer-name strong').addEventListener('dblclick',event=>{event.preventDefault();event.stopPropagation();beginLayerRename(layer,event.currentTarget,row);});
        row.addEventListener('click',event=>{if(event.target.closest('.ps-layer-eye')){layer.visible=!layer.visible;updateLayer(layer,{visible:layer.visible},layer.visible?'Show Layer':'Hide Layer');render();}else if(!event.target.closest('.ps-layer-name-input')){selectLayerFromPanel(event,layer,ordered);renderLayers();renderProperties();updateMoveable();}});
        row.addEventListener('dragstart',event=>{if(!state.selectedLayerIds.has(layer.id))selectOnlyLayer(layer.id);else state.activeLayerId=layer.id;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',layer.id);row.classList.add('dragging');});
        row.addEventListener('dragend',()=>{row.classList.remove('dragging');panel.querySelectorAll('.drag-before,.drag-after').forEach(item=>item.classList.remove('drag-before','drag-after'));});
        row.addEventListener('dragover',event=>{event.preventDefault();if(event.dataTransfer.getData('text/plain')===layer.id)return;const after=event.clientY>row.getBoundingClientRect().top+row.offsetHeight/2;row.classList.toggle('drag-before',!after);row.classList.toggle('drag-after',after);event.dataTransfer.dropEffect='move';});
        row.addEventListener('dragleave',()=>row.classList.remove('drag-before','drag-after'));
        row.addEventListener('drop',event=>{event.preventDefault();const draggedId=event.dataTransfer.getData('text/plain'),after=event.clientY>row.getBoundingClientRect().top+row.offsetHeight/2;reorderLayer(draggedId,layer.id,after);});
        panel.append(row);
    });
    syncLayerControls();
}

function switchPanel(panel){state.panel=panel;document.querySelectorAll('[data-panel-tab]').forEach(button=>button.classList.toggle('active',button.dataset.panelTab===panel));document.querySelectorAll('[data-panel-view]').forEach(view=>view.classList.toggle('active',view.dataset.panelView===panel));if(panel==='properties')renderProperties();if(panel==='history')renderHistory();}
function renderProperties(){if(state.panel!=='properties')return;const panel=document.getElementById('propertiesPanel'),layer=activeLayer();if(!layer){panel.innerHTML='<div class="ps-panel-empty">Select a layer to view its properties.</div>';return;}const typeIcon=layer.type==='text'?'tools-htype':'pix_layer',typeLabel=layer.type==='text'?'Text Layer':'Pixel Layer';panel.innerHTML=`<div class="ps-property-identity"><span data-property-thumb></span><strong>${escapeHtml(layer.name)}<small>${iconMarkup(typeIcon)} ${typeLabel}</small></strong></div><section class="ps-property-section"><h3>${iconMarkup('lrs-arrow_down')} Transform</h3><div class="ps-property-grid"><label>W<input data-layer-property="width" type="number" min="1" value="${Math.round(layer.width)}"></label><label>X<input data-layer-property="x" type="number" value="${Math.round(layer.x)}"></label><label>H<input data-layer-property="height" type="number" min="1" value="${Math.round(layer.height)}"></label><label>Y<input data-layer-property="y" type="number" value="${Math.round(layer.y)}"></label><label>°<input data-layer-property="rotation" type="number" step="0.1" value="${Number(layer.rotation).toFixed(1)}"></label><label>%<input data-layer-property="opacity" type="number" min="0" max="100" value="${layer.opacity}"></label></div></section><section class="ps-property-section"><h3>${iconMarkup('lrs-arrow_down')} Align and Distribute</h3><div class="ps-align-buttons"><button type="button" data-align-layer="left">${iconMarkup('align-h0')}</button><button type="button" data-align-layer="center">${iconMarkup('align-h1')}</button><button type="button" data-align-layer="right">${iconMarkup('align-h2')}</button></div><button type="button" class="ps-restore-ratio" data-action="restoreAspectRatio">${iconMarkup('reload')}<span>Restore aspect ratio</span></button></section>`;panel.querySelector('[data-property-thumb]').replaceWith(layerImage(layer,'properties'));}
function renderHistory(){if(state.panel!=='history')return;const panel=document.getElementById('historyPanel'),project=activeProject();if(!project){panel.innerHTML='<div class="ps-panel-empty">Open a document to see its history.</div>';return;}const history=historyFor(project);panel.innerHTML=`<div class="ps-history-document"><span class="ps-history-icon">${iconMarkup('pix_layer')}</span><strong>${escapeHtml(project.name)}</strong></div><ol class="ps-history-list">${history.entries.map((entry,index)=>`<li class="ps-history-entry${index===history.index?' current':''}${index>history.index?' future':''}"><button type="button" data-history-index="${index}"><span class="ps-history-icon">${iconMarkup(entry.icon)}</span><span>${escapeHtml(entry.label)}</span></button></li>`).join('')}</ol>`;panel.querySelectorAll('[data-history-index]').forEach(button=>button.addEventListener('click',()=>restoreHistoryTo(Number(button.dataset.historyIndex))));}

function updateMoveable(){state.moveable?.destroy();state.moveable=null;const project=activeProject(),layer=activeLayer();if(!project||!layer||state.tool!=='move'||!layer.visible)return;const canvas=document.getElementById('canvas'),target=canvas.querySelector(`[data-layer-id="${layer.id}"]`);if(!target)return;const otherLayers=[...canvas.querySelectorAll('.ps-canvas-layer')].filter(element=>element!==target&&element.style.display!=='none'),showControls=document.getElementById('transformControls').checked;state.moveable=new Moveable(canvas,{target,draggable:true,resizable:showControls,rotatable:showControls,hideDefaultLines:!showControls,snappable:true,snapThreshold:7,snapGap:true,isDisplaySnapDigit:true,snapDirections:{left:true,right:true,top:true,bottom:true,center:true,middle:true},verticalGuidelines:[0,project.width*state.zoom/2,project.width*state.zoom],horizontalGuidelines:[0,project.height*state.zoom/2,project.height*state.zoom],elementGuidelines:otherLayers,origin:false,keepRatio:true,renderDirections:showControls?['nw','n','ne','w','e','sw','s','se']:[]});state.moveable.on('drag',event=>{target.style.left=`${event.left}px`;target.style.top=`${event.top}px`;}).on('dragEnd',()=>{layer.x=parseFloat(target.style.left)/state.zoom;layer.y=parseFloat(target.style.top)/state.zoom;updateLayer(layer,{x:layer.x,y:layer.y},'Move');}).on('resizeStart',event=>event.setRatio(event.inputEvent?.shiftKey?0:layerOriginalRatio(layer))).on('resize',event=>{target.style.width=`${event.width}px`;target.style.height=`${event.height}px`;target.style.transform=event.drag.transform.replace(/translate\([^)]*\)/,'')+` rotate(${layer.rotation}deg)`;target.style.left=`${event.drag.left}px`;target.style.top=`${event.drag.top}px`;}).on('resizeEnd',()=>{layer.x=parseFloat(target.style.left)/state.zoom;layer.y=parseFloat(target.style.top)/state.zoom;layer.width=parseFloat(target.style.width)/state.zoom;layer.height=parseFloat(target.style.height)/state.zoom;target.style.transform=`rotate(${layer.rotation}deg)`;updateLayer(layer,{x:layer.x,y:layer.y,width:layer.width,height:layer.height},'Transform');}).on('rotate',event=>{target.style.transform=event.transform;}).on('rotateEnd',event=>{layer.rotation=event.lastEvent?.beforeRotate??layer.rotation;updateLayer(layer,{rotation:layer.rotation},'Rotate');});}
async function updateLayer(layer,changes,historyLabel=null){Object.assign(layer,changes);if(historyLabel)recordHistory(historyLabel);else refreshDirty(activeProject());renderProperties();return layer;}
function layerOriginalRatio(layer){const width=Number(layer.original_width||layer.width),height=Number(layer.original_height||layer.height);return width>0&&height>0?width/height:1;}
function restoreActiveLayerAspectRatio(){const layer=activeLayer();if(!layer)return;const ratio=layerOriginalRatio(layer);let width=Number(layer.width),height=Number(layer.height);if(width>=height)height=width/ratio;else width=height*ratio;updateLayer(layer,{width:Number(width.toFixed(3)),height:Number(height.toFixed(3))},'Restore Aspect Ratio').then(render);}
function alignActiveLayers(mode){
    const project=activeProject(),layers=selectedLayers();if(!project||!layers.length)return;
    const horizontal=mode==='hgap',vertical=mode==='vgap';
    if((horizontal||vertical)&&layers.length<3){toast('Select at least three layers to distribute gaps.');return;}
    if(mode==='grid'){layers.forEach(layer=>{layer.x=Math.round(layer.x/10)*10;layer.y=Math.round(layer.y/10)*10;});}
    else if(horizontal||vertical){const axis=horizontal?'x':'y',size=horizontal?'width':'height',ordered=[...layers].sort((a,b)=>a[axis]-b[axis]),start=ordered[0][axis],end=ordered.at(-1)[axis]+ordered.at(-1)[size],total=ordered.reduce((sum,layer)=>sum+layer[size],0),gap=(end-start-total)/(ordered.length-1);let cursor=start;ordered.forEach(layer=>{layer[axis]=cursor;cursor+=layer[size]+gap;});}
    else{const bounds=layers.length===1?{left:0,top:0,right:project.width,bottom:project.height}:{left:Math.min(...layers.map(layer=>layer.x)),top:Math.min(...layers.map(layer=>layer.y)),right:Math.max(...layers.map(layer=>layer.x+layer.width)),bottom:Math.max(...layers.map(layer=>layer.y+layer.height))};layers.forEach(layer=>{if(mode==='left')layer.x=bounds.left;if(mode==='right')layer.x=bounds.right-layer.width;if(mode==='center'||mode==='hcenter')layer.x=(bounds.left+bounds.right-layer.width)/2;if(mode==='top')layer.y=bounds.top;if(mode==='bottom')layer.y=bounds.bottom-layer.height;if(mode==='vcenter')layer.y=(bounds.top+bounds.bottom-layer.height)/2;});}
    recordHistory(mode==='grid'?'Align to Grid':horizontal||vertical?'Distribute Layers':'Align Layers');render();
}

async function addLayer(project,dataUrl,width,height,name,x=0,y=0,historyLabel='New Layer',options={}){const layer=newLayer(project,{name,dataUrl,width,height,x,y,z_index:Math.max(-1,...project.layers.map(item=>item.z_index))+1,...options});project.layers.push(layer);selectOnlyLayer(layer.id);recordHistory(historyLabel);render();return layer;}
async function createBlankLayer(){const project=activeProject();if(!project){toast('Open a document first.');return;}const canvas=transparentCanvas(project.width,project.height);await addLayer(project,canvasToDataUrl(canvas),project.width,project.height,`Layer ${project.layers.length+1}`);}
async function duplicateLayer(){const project=activeProject(),layer=activeLayer();if(!project||!layer){toast('Select a layer first.');return;}await addLayer(project,layer.image_url,layer.width,layer.height,`${layer.name} copy`,layer.x+10,layer.y+10,'Duplicate Layer',{type:layer.type,text:layer.text,textData:layer.textData,blendMode:layer.blendMode});}
function renameLayer(){const layer=activeLayer();if(!layer)return;const name=prompt('Layer name',layer.name);if(name?.trim()){layer.name=name.trim();recordHistory('Rename Layer');render();}}
function makeTextCanvas(text,fontSize=36,color='#000'){const lines=String(text).split(/\r?\n/),probe=transparentCanvas(1,1),probeContext=probe.getContext('2d');probeContext.font=`${fontSize}px Arial`;const width=Math.max(2,Math.ceil(Math.max(...lines.map(line=>probeContext.measureText(line||' ').width))+8)),lineHeight=Math.ceil(fontSize*1.25),canvas=transparentCanvas(width,lineHeight*lines.length+6),context=canvas.getContext('2d');context.font=`${fontSize}px Arial`;context.textBaseline='top';context.fillStyle=color;lines.forEach((line,index)=>context.fillText(line,4,3+index*lineHeight));return canvas;}
async function addTextLayerAt(x,y){const project=activeProject();if(!project){toast('Open a document first.');return;}const text=prompt('Text for the new layer','Text');if(!text)return;const fontSize=36,canvas=makeTextCanvas(text,fontSize);const textData={text,transform:[1,0,0,1,x,y+fontSize],style:{font:{name:'ArialMT'},fontSize,fillColor:{r:0,g:0,b:0}}};await addLayer(project,canvasToDataUrl(canvas),canvas.width,canvas.height,text.slice(0,40),x,y,'New Text Layer',{type:'text',text,textData});}
function addTextLayerAtCenter(){const project=activeProject();if(project)addTextLayerAt(Math.max(0,(project.width-200)/2),Math.max(0,(project.height-50)/2));}

function selectArea(area){if(!activeProject())return;state.selection=area;renderSelection();}
function clearSelection(){state.selection=null;renderSelection();}
function renderSelection(){const box=document.getElementById('selectionBox');if(!state.selection||!activeProject()){box.hidden=true;return;}box.hidden=false;Object.assign(box.style,{left:`${state.selection.x*state.zoom}px`,top:`${state.selection.y*state.zoom}px`,width:`${state.selection.width*state.zoom}px`,height:`${state.selection.height*state.zoom}px`});}
async function copySelection(){const project=activeProject();if(!project)return;const area=state.selection||{x:0,y:0,width:project.width,height:project.height},composite=await renderComposite(project),out=transparentCanvas(Math.round(area.width),Math.round(area.height));out.getContext('2d').drawImage(composite,area.x,area.y,area.width,area.height,0,0,out.width,out.height);state.clipboard={dataUrl:canvasToDataUrl(out),width:out.width,height:out.height,x:area.x,y:area.y};try{const blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));await navigator.clipboard?.write([new ClipboardItem({'image/png':blob})]);}catch{}toast(`Copied ${out.width} × ${out.height}px.`);}
async function pasteClipboard(inPlace=false){const project=activeProject();if(!project)return;let clip=state.clipboard;if(!clip){try{const item=(await navigator.clipboard.read()).find(entry=>entry.types.includes('image/png'));if(item){const png=await imageFileToPng(await item.getType('image/png'));clip={...png,x:0,y:0};}}catch{}}if(!clip){toast('Nothing copied yet.');return;}const x=inPlace?clip.x:(project.width-clip.width)/2,y=inPlace?clip.y:(project.height-clip.height)/2;await addLayer(project,clip.dataUrl,clip.width,clip.height,`Pasted layer ${project.layers.length+1}`,x,y,'Paste');}

function closeTab(id){if(!id)return;if(state.dirtyProjects.has(id)&&!confirm('Close this document without downloading its latest PSD?'))return;const index=state.tabs.indexOf(id),wasActive=state.activeProjectId===id;state.tabs=state.tabs.filter(tab=>tab!==id);state.projects.delete(id);state.zooms.delete(id);state.histories.delete(id);state.savedSignatures.delete(id);state.dirtyProjects.delete(id);if(wasActive)state.activeProjectId=state.tabs[Math.max(0,index-1)]||state.tabs[0]||null;state.zoom=state.activeProjectId?(state.zooms.get(state.activeProjectId)||1):1;selectOnlyLayer(topLayer(activeProject())?.id||null);clearSelection();render();}
function setZoom(value){state.zoom=Math.min(4,Math.max(.05,value));if(state.activeProjectId)state.zooms.set(state.activeProjectId,state.zoom);renderCanvas();renderTabs();}
function fitScreen(){const project=activeProject(),viewport=document.getElementById('stageViewport');if(project)setZoom(Math.min(1,(viewport.clientWidth-100)/project.width,(viewport.clientHeight-150)/project.height));}

async function buildMenus(){const menus=await fetch('/photoshop-menus.json').then(response=>response.json()),bar=document.getElementById('menuBar');menus.filter(menu=>menu.visible).forEach(menu=>{const wrap=document.createElement('div');wrap.className='ps-menu';const button=document.createElement('button');button.className='ps-menu-button';button.textContent=menu.label;button.type='button';const panel=document.createElement('div');panel.className='ps-menu-panel';panel.hidden=true;menu.items.filter(item=>item.visible).forEach(item=>panel.append(buildMenuItem(item)));button.addEventListener('click',event=>{event.stopPropagation();const opening=panel.hidden;closeMenus();panel.hidden=!opening;wrap.classList.toggle('open',opening);});wrap.append(button,panel);bar.append(wrap);});}
function buildMenuItem(item){if(item.separator){const line=document.createElement('div');line.className='ps-menu-separator';return line;}const button=document.createElement('button');button.type='button';button.className='ps-menu-item';button.disabled=item.enabled===false;const label=document.createElement('span');label.textContent=item.label;const suffix=document.createElement('span');suffix.className='ps-menu-shortcut';if(item.children)suffix.innerHTML=iconMarkup('lrs-arrow_right');else suffix.textContent=item.shortcut||'';button.append(label,suffix);if(item.children){const sub=document.createElement('span');sub.className='ps-submenu';item.children.filter(child=>child.visible).forEach(child=>sub.append(buildMenuItem(child)));button.append(sub);}if(item.action)button.addEventListener('click',event=>{event.stopPropagation();closeMenus();actions[item.action]?.();});return button;}
function closeMenus(){document.querySelectorAll('.ps-menu-panel').forEach(panel=>panel.hidden=true);document.querySelectorAll('.ps-menu').forEach(menu=>menu.classList.remove('open'));}
function toolMeta(id){for(const group of toolGroups){const tool=group.tools.find(item=>item.id===id);if(tool)return {...tool,group};}return null;}
function closeToolFlyouts(except=null){document.querySelectorAll('.ps-tool-group.open').forEach(group=>{if(group!==except)group.classList.remove('open');});}
function buildTools(){const panel=document.getElementById('toolsPanel');toolGroups.forEach(group=>{group.activeId=group.tools[0].id;const wrapper=document.createElement('div');wrapper.className=`ps-tool-group${group.id==='move'?' active':''}`;wrapper.dataset.toolGroup=group.id;const main=document.createElement('button');main.type='button';main.className='ps-tool';main.dataset.tool=group.activeId;main.title=group.tools[0].name;main.innerHTML=`${iconMarkup(group.tools[0].icon,'ps-tool-icon')}<kbd>${group.key}</kbd>`;wrapper.append(main);if(group.tools.length>1){const toggle=document.createElement('button');toggle.type='button';toggle.className='ps-tool-flyout-toggle';toggle.innerHTML=iconMarkup('lrs-arrow_right','ps-tool-flyout-arrow');const flyout=document.createElement('div');flyout.className='ps-tool-flyout';group.tools.forEach(tool=>{const item=document.createElement('button');item.type='button';item.className='ps-tool-flyout-item';item.dataset.tool=tool.id;item.innerHTML=`${iconMarkup(tool.icon,'ps-tool-icon')}<span>${escapeHtml(tool.name)}</span><kbd>${group.key}</kbd>`;flyout.append(item);});toggle.addEventListener('click',event=>{event.stopPropagation();const opening=!wrapper.classList.contains('open');closeToolFlyouts();wrapper.classList.toggle('open',opening);});wrapper.addEventListener('contextmenu',event=>{event.preventDefault();closeToolFlyouts();wrapper.classList.add('open');});wrapper.append(toggle,flyout);}panel.append(wrapper);});}
function selectTool(tool){const meta=toolMeta(tool);if(!meta)return;meta.group.activeId=tool;state.tool=tool;document.querySelectorAll('.ps-tool-group').forEach(wrapper=>wrapper.classList.toggle('active',wrapper.dataset.toolGroup===meta.group.id));const groupButton=document.querySelector(`[data-tool-group="${meta.group.id}"] > .ps-tool`);if(groupButton){groupButton.dataset.tool=tool;groupButton.title=meta.name;groupButton.innerHTML=`${iconMarkup(meta.icon,'ps-tool-icon')}<kbd>${meta.group.key}</kbd>`;}document.getElementById('activeToolIcon').innerHTML=iconMarkup(meta.icon);document.getElementById('activeToolName').textContent=meta.name;closeToolFlyouts();if(!['move','marquee','zoom','zoom-in','zoom-out','horizontal-type'].includes(tool))toast(`${meta.name} will be added in a later version.`);updateMoveable();}

function renderTemplateCategories(){const nav=document.getElementById('templateCategories');nav.replaceChildren(...documentTemplateCategories.map(category=>{const button=document.createElement('button');button.type='button';button.textContent=category.label;button.classList.toggle('active',category.id===activeTemplateCategory);button.addEventListener('click',()=>{activeTemplateCategory=category.id;selectedDocumentTemplateId=null;renderTemplateCategories();renderTemplateGrid();});return button;}));}
function renderTemplateGrid(){const grid=document.getElementById('templateGrid'),category=documentTemplateCategories.find(item=>item.id===activeTemplateCategory);grid.replaceChildren(...(category?.templates||[]).map(template=>{const card=document.createElement('button');card.type='button';card.className='ps-template-card';card.classList.toggle('selected',template.id===selectedDocumentTemplateId);const scale=Math.min(166/Number(template.width),106/Number(template.height)),preview=document.createElement('span');preview.className='ps-template-preview';preview.style.width=`${Math.max(2,Number(template.width)*scale)}px`;preview.style.height=`${Math.max(2,Number(template.height)*scale)}px`;const title=document.createElement('strong');title.textContent=template.title||'';title.hidden=!template.title;const dimensions=document.createElement('span');dimensions.className='ps-template-dimensions';dimensions.textContent=template.display;card.append(preview,title,dimensions);card.addEventListener('click',()=>selectDocumentTemplate(template));return card;}));}
function selectDocumentTemplate(template){selectedDocumentTemplateId=template.id;document.getElementById('projectWidth').value=template.width;document.getElementById('projectHeight').value=template.height;document.getElementById('documentUnit').value=template.unit;document.getElementById('documentDpi').value=template.dpi;renderTemplateGrid();}
function documentPixelDimensions(){const width=Number(document.getElementById('projectWidth').value),height=Number(document.getElementById('projectHeight').value),dpi=Number(document.getElementById('documentDpi').value),unit=document.getElementById('documentUnit').value,multiplier=unit==='in'?dpi:unit==='mm'?dpi/25.4:1;return {width:Math.round(width*multiplier),height:Math.round(height*multiplier)};}
async function loadDocumentTemplates(){const response=await fetch('/photoshop-templates.json');if(!response.ok)throw new Error('Could not load document templates.');documentTemplateCategories=(await response.json()).categories||[];activeTemplateCategory=documentTemplateCategories[0]?.id||'social';renderTemplateCategories();renderTemplateGrid();}

document.addEventListener('click',event=>{if(!event.target.closest('.ps-menu'))closeMenus();if(!event.target.closest('.ps-tool-group'))closeToolFlyouts();if(!event.target.closest('#opacityControl'))document.getElementById('opacityPopover').hidden=true;const action=event.target.closest('[data-action]')?.dataset.action;if(action)actions[action]?.();const tool=event.target.closest('[data-tool]')?.dataset.tool;if(tool)selectTool(tool);const panel=event.target.closest('[data-panel-tab]')?.dataset.panelTab;if(panel)switchPanel(panel);const align=event.target.closest('[data-align-layer]')?.dataset.alignLayer;if(align)alignActiveLayers(align);});
document.addEventListener('keydown',event=>{const mod=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if(mod&&key==='z'){event.preventDefault();event.shiftKey?actions.redo():actions.undo();return;}if(mod&&key==='y'){event.preventDefault();actions.redo();return;}if(mod&&key==='s'){event.preventDefault();exportActiveProjectAsPsd();return;}if(mod&&(key==='+'||key==='=')){event.preventDefault();actions.zoomIn();return;}if(mod&&key==='-'){event.preventDefault();actions.zoomOut();return;}if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;let action=null;if(mod&&key==='n')action='newProject';if(mod&&key==='o')action='openLocal';if(mod&&key==='a')action='selectAll';if(mod&&key==='c')action='copy';if(mod&&key==='v')action='paste';if(mod&&key==='d')action='deselect';if(mod&&event.key==='0')action='fitScreen';if(mod&&event.key==='1')action='actualPixels';if(action){event.preventDefault();actions[action]?.();}if(!mod&&['v','m','t','z'].includes(key))selectTool(key==='m'?'marquee':key==='v'?'move':key==='t'?'horizontal-type':'zoom');});
document.getElementById('newProjectForm').addEventListener('submit',event=>{event.preventDefault();if(event.submitter?.value==='cancel'){document.getElementById('newProjectDialog').close();return;}const dimensions=documentPixelDimensions();if(dimensions.width<1||dimensions.height<1||dimensions.width>8192||dimensions.height>8192){toast('Document dimensions must resolve to between 1 and 8,192 pixels.');return;}const project={id:nextProjectId(),name:document.getElementById('newProjectName').value,width:dimensions.width,height:dimensions.height,layers:[]},canvas=transparentCanvas(dimensions.width,dimensions.height);project.layers.push(newLayer(project,{name:'Layer 1',dataUrl:canvasToDataUrl(canvas),width:dimensions.width,height:dimensions.height,z_index:0}));createLocalProject({...project,historyLabel:'New',clean:false});document.getElementById('newProjectDialog').close();});
document.getElementById('swapDimensions').addEventListener('click',()=>{const width=document.getElementById('projectWidth'),height=document.getElementById('projectHeight'),next=width.value;width.value=height.value;height.value=next;selectedDocumentTemplateId=null;renderTemplateGrid();});
for(const id of ['projectWidth','projectHeight','documentUnit','documentDpi'])document.getElementById(id).addEventListener('input',()=>{selectedDocumentTemplateId=null;renderTemplateGrid();});
document.getElementById('localFileInput').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{await openLocalFile(file);}catch(error){toast(error.message||'Could not open that local file.');}});
const opacityInput=document.getElementById('layerOpacity'),opacitySlider=document.getElementById('layerOpacitySlider'),opacityPopover=document.getElementById('opacityPopover');
function showOpacitySlider(){if(activeLayer())opacityPopover.hidden=false;}
document.getElementById('opacityTrigger').addEventListener('click',()=>{if(activeLayer())opacityPopover.hidden=!opacityPopover.hidden;});
opacityInput.addEventListener('click',showOpacitySlider);
opacityInput.addEventListener('change',event=>{const layer=activeLayer();if(!layer)return;const value=Math.max(0,Math.min(100,Number(event.target.value)||0));event.target.value=value;opacitySlider.value=value;updateLayer(layer,{opacity:value},'Opacity Change').then(renderCanvas);});
opacitySlider.addEventListener('focus',()=>{const layer=activeLayer();if(layer)opacitySlider.dataset.start=String(layer.opacity);});
opacitySlider.addEventListener('pointerdown',()=>{const layer=activeLayer();if(layer)opacitySlider.dataset.start=String(layer.opacity);});
opacitySlider.addEventListener('input',event=>{const layer=activeLayer();if(!layer)return;layer.opacity=Number(event.target.value);opacityInput.value=event.target.value;refreshDirty(activeProject());renderCanvas();renderProperties();});
opacitySlider.addEventListener('change',()=>{const layer=activeLayer();if(layer&&Number(opacitySlider.dataset.start)!==layer.opacity)recordHistory('Opacity Change');});
document.getElementById('layerBlendMode').addEventListener('change',event=>{const layer=activeLayer();if(layer)updateLayer(layer,{blendMode:event.target.value},'Blending Change').then(renderCanvas);});
document.getElementById('transformControls').addEventListener('change',updateMoveable);
document.getElementById('propertiesPanel').addEventListener('change',event=>{const input=event.target.closest('[data-layer-property]'),layer=activeLayer();if(!input||!layer)return;const property=input.dataset.layerProperty,value=Number(input.value);if(Number.isFinite(value))updateLayer(layer,{[property]:value},property==='opacity'?'Opacity Change':'Transform').then(render);});
document.getElementById('canvas').addEventListener('pointerdown',event=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),point={x:(event.clientX-rect.left)/state.zoom,y:(event.clientY-rect.top)/state.zoom};if(state.tool==='horizontal-type'){addTextLayerAt(point.x,point.y);return;}if(['zoom','zoom-in','zoom-out'].includes(state.tool)){const zoomOut=state.tool==='zoom-out'||(state.tool==='zoom'&&event.altKey);setZoom(state.zoom*(zoomOut ? .8 : 1.25));return;}if(state.tool!=='marquee')return;const start=point;canvas.setPointerCapture(event.pointerId);const move=next=>{const x=(next.clientX-rect.left)/state.zoom,y=(next.clientY-rect.top)/state.zoom;selectArea({x:Math.max(0,Math.min(start.x,x)),y:Math.max(0,Math.min(start.y,y)),width:Math.min(activeProject().width,Math.abs(x-start.x)),height:Math.min(activeProject().height,Math.abs(y-start.y))});};const up=()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);});
window.addEventListener('resize',()=>{if(activeProject())fitScreen();});

async function init(){buildTools();updateSaveUi();try{await Promise.all([buildMenus(),loadDocumentTemplates()]);}catch(error){toast(error.message);}}
init();
