import Moveable from 'moveable';
import { readPsd, writePsd } from 'ag-psd';
import '../css/photoshop.css';

const state = {
    projects: new Map(), tabs: [], activeProjectId: null, activeLayerId: null, activeFolderId: null,
    selectedLayerIds: new Set(), selectedFolderIds: new Set(),
    tool: 'move', zoom: 1, zooms: new Map(), selection: null, clipboard: null,
    moveable: null, panel: 'layers', histories: new Map(), imageElements: new Map(), imageSources: new Map(), thumbnailCache: new Map(),
    dirtyProjects: new Set(), savedSignatures: new Map(), loadingFile: null,
    busy: false, layerizeRunning: 0, nextProjectId: 1, nextLayerId: 1, nextFolderId: 1,
};

let documentTemplateCategories = [];
let activeTemplateCategory = 'social';
let selectedDocumentTemplateId = null;
const iconBase = '/ps-icons/';
const photoshopApp=document.getElementById('photoshopApp');
const layerizeConfig={storeUrl:photoshopApp.dataset.layerizeStoreUrl,historyUrl:photoshopApp.dataset.layerizeHistoryUrl,csrfToken:document.querySelector('meta[name="csrf-token"]')?.content||''};

const toolGroups = [
    {id:'move',key:'V',tools:[{id:'move',name:'Move Tool',icon:'tools-move'},{id:'artboard',name:'Artboard Tool',icon:'tools-artb'}]},
    {id:'marquee',key:'M',tools:[{id:'marquee',name:'Rectangular Marquee Tool',icon:'tools-rselect'},{id:'ellipse-marquee',name:'Elliptical Marquee Tool',icon:'tools-eselect'},{id:'single-row-marquee',name:'Single Row Marquee Tool',icon:'tools-sselect'}]},
    {id:'lasso',key:'L',tools:[{id:'lasso',name:'Lasso Tool',icon:'tools-lasso'},{id:'polygonal-lasso',name:'Polygonal Lasso Tool',icon:'tools-plasso'},{id:'magnetic-lasso',name:'Magnetic Lasso Tool',icon:'tools-mlasso'}]},
    {id:'selection',key:'W',tools:[{id:'object-selection',name:'Object Selection Tool',icon:'tools-oselect'},{id:'quick-selection',name:'Quick Selection Tool',icon:'tools-qselect'},{id:'magic-wand',name:'Magic Wand Tool',icon:'tools-mwand'}]},
    {id:'crop',key:'C',tools:[{id:'crop',name:'Crop Tool',icon:'tools-rcrop'},{id:'perspective-crop',name:'Perspective Crop Tool',icon:'tools-pcrop'},{id:'slice',name:'Slice Tool',icon:'tools-slice'}]},
    {id:'eyedropper',key:'I',tools:[{id:'eyedropper',name:'Eyedropper Tool',icon:'tools-eyedropper'},{id:'color-sampler',name:'Color Sampler Tool',icon:'tools-csamp'},{id:'ruler',name:'Ruler Tool',icon:'tools-ruler'}]},
    {id:'retouch',key:'J',tools:[{id:'spot-healing',name:'Spot Healing Brush Tool',icon:'tools-shbrush'},{id:'healing-brush',name:'Healing Brush Tool',icon:'tools-hbrush'},{id:'patch',name:'Patch Tool',icon:'tools-patch'},{id:'content-aware-move',name:'Content-Aware Move Tool',icon:'tools-mremove'},{id:'red-eye',name:'Red Eye Tool',icon:'tools-redeye'}]},
    {id:'brush',key:'B',tools:[{id:'brush',name:'Brush Tool',icon:'tools-brush'},{id:'pencil',name:'Pencil Tool',icon:'tools-pencil'},{id:'color-replacement',name:'Color Replacement Tool',icon:'tools-crepl'}]},
    {id:'clone',key:'S',tools:[{id:'clone-stamp',name:'Clone Stamp Tool',icon:'tools-clone'}]},
    {id:'eraser',key:'E',tools:[{id:'eraser',name:'Eraser Tool',icon:'tools-eraser'},{id:'background-eraser',name:'Background Eraser Tool',icon:'tools-beraser'},{id:'magic-eraser',name:'Magic Eraser Tool',icon:'tools-meraser'}]},
    {id:'fill',key:'G',tools:[{id:'gradient',name:'Gradient Tool',icon:'tools-gradient'},{id:'paint-bucket',name:'Paint Bucket Tool',icon:'tools-pbucket'}]},
    {id:'focus',key:'R',tools:[{id:'blur',name:'Blur Tool',icon:'tools-blur'},{id:'sharpen',name:'Sharpen Tool',icon:'tools-sharpen'},{id:'smudge',name:'Smudge Tool',icon:'tools-smudge'}]},
    {id:'tone',key:'O',tools:[{id:'dodge',name:'Dodge Tool',icon:'tools-dodge'},{id:'burn',name:'Burn Tool',icon:'tools-burn'},{id:'sponge',name:'Sponge Tool',icon:'tools-sponge'}]},
    {id:'pen',key:'P',tools:[{id:'pen',name:'Pen Tool',icon:'tools-pen'},{id:'freeform-pen',name:'Freeform Pen Tool',icon:'tools-fpen'},{id:'curvature-pen',name:'Curvature Pen Tool',icon:'tools-cpen'},{id:'add-anchor',name:'Add Anchor Point Tool',icon:'tools-aapoint'},{id:'delete-anchor',name:'Delete Anchor Point Tool',icon:'tools-dapoint'},{id:'convert-point',name:'Convert Point Tool',icon:'tools-capoint'}]},
    {id:'type',key:'T',tools:[{id:'horizontal-type',name:'Horizontal Type Tool',icon:'tools-htype'},{id:'vertical-type',name:'Vertical Type Tool',icon:'tools-vtype'}]},
    {id:'path',key:'A',tools:[{id:'path-selection',name:'Path Selection Tool',icon:'tools-pselect'},{id:'direct-selection',name:'Direct Selection Tool',icon:'tools-dselect'}]},
    {id:'shape',key:'U',tools:[{id:'rectangle',name:'Rectangle Tool',icon:'tools-rect'},{id:'ellipse',name:'Ellipse Tool',icon:'tools-ellipse'},{id:'polygon',name:'Polygon Tool',icon:'tools-pshape'},{id:'line',name:'Line Tool',icon:'tools-line'},{id:'custom-shape',name:'Custom Shape Tool',icon:'tools-cshape'}]},
    {id:'hand',key:'H',tools:[{id:'hand',name:'Hand Tool',icon:'tools-hand'},{id:'rotate-view',name:'Rotate View Tool',icon:'tools-rview'}]},
    {id:'zoom',key:'Z',tools:[{id:'zoom',name:'Zoom Tool',icon:'tools-zoom'},{id:'zoom-in',name:'Zoom In Tool',icon:'zoomIn'},{id:'zoom-out',name:'Zoom Out Tool',icon:'zoomOut'}]},
];

const actions = {
    newProject: () => document.getElementById('newProjectDialog').showModal(),
    openLocal: () => document.getElementById('localFileInput').click(),
    placeImage: () => activeProject()?document.getElementById('placeImageInput').click():toast('Open a document first.'),
    imageSize: openImageSizeDialog, canvasSize: openCanvasSizeDialog,
    closeProject: () => closeTab(state.activeProjectId),
    saveProject: exportActiveProjectAsPsd,
    undo: () => restoreHistory(-1), redo: () => restoreHistory(1),
    exit: () => window.close(),
    selectAll: () => selectArea({x:0,y:0,width:activeProject()?.width||0,height:activeProject()?.height||0}),
    deselect: clearSelection, copy: copySelection, paste: () => pasteClipboard(false),
    pasteInPlace: () => pasteClipboard(true), newBlankLayer: createBlankLayer, newLayerFolder: createLayerFolder,
    deleteLayers: requestDeleteSelected,
    addTextLayer: () => addTextLayerAtCenter(), duplicateLayer, renameLayer,
    layerize: startLayerize, layerizeHistory: showLayerizeHistory,
    restoreAspectRatio: restoreActiveLayerAspectRatio,
    zoomIn: () => setZoom(state.zoom*1.2), zoomOut: () => setZoom(state.zoom/1.2),
    fitScreen, actualPixels: () => setZoom(1),
    help: () => toast('Everything stays in this browser tab. Open a PSD or image, then use Save PSD to download your work.'),
};

function activeProject(){return state.projects.get(state.activeProjectId);}
function activeLayer(){return activeProject()?.layers.find(layer=>layer.id===state.activeLayerId);}
function activeFolder(){return activeProject()?.folders?.find(folder=>folder.id===state.activeFolderId);}
function selectedLayers(){const project=activeProject();if(!project)return [];const selected=project.layers.filter(layer=>state.selectedLayerIds.has(layer.id));return selected.length?selected:(activeLayer()?[activeLayer()]:[]);}
function selectOnlyLayer(id){state.activeLayerId=id||null;state.activeFolderId=null;state.selectedLayerIds=new Set(id?[id]:[]);state.selectedFolderIds.clear();}
function selectOnlyFolder(id){state.activeLayerId=null;state.activeFolderId=id||null;state.selectedLayerIds.clear();state.selectedFolderIds=new Set(id?[id]:[]);}
function selectLayerFromPanel(event,layer,ordered){if(event.shiftKey&&state.activeLayerId){const from=ordered.findIndex(item=>item.id===state.activeLayerId),to=ordered.findIndex(item=>item.id===layer.id);if(from>=0&&to>=0){state.selectedLayerIds=new Set(ordered.slice(Math.min(from,to),Math.max(from,to)+1).map(item=>item.id));state.activeLayerId=layer.id;return;}}if(event.ctrlKey||event.metaKey){if(state.selectedLayerIds.has(layer.id)){state.selectedLayerIds.delete(layer.id);if(state.activeLayerId===layer.id)state.activeLayerId=state.selectedLayerIds.values().next().value||null;}else{state.selectedLayerIds.add(layer.id);state.activeLayerId=layer.id;}return;}selectOnlyLayer(layer.id);}
function topLayer(project){return project?.layers.reduce((top,layer)=>!top||layer.z_index>top.z_index?layer:top,null);}
function nextProjectId(){return `document-${state.nextProjectId++}`;}
function nextLayerId(){return `layer-${state.nextLayerId++}`;}
function nextFolderId(){return `folder-${state.nextFolderId++}`;}
function clonePlain(value){return value==null?value:JSON.parse(JSON.stringify(value));}
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML;}
function iconUrl(icon){return `${iconBase}${icon}.png`;}
function iconMarkup(icon,className='ps-icon',alt=''){return `<img class="${className}" src="${iconUrl(icon)}" alt="${escapeHtml(alt)}">`;}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3600);}
function setBusy(value){state.busy=value;updateSaveUi();}

function projectSnapshot(project){return {name:project.name,width:project.width,height:project.height,layers:project.layers.map(layer=>({...layer,textData:clonePlain(layer.textData)})),folders:(project.folders||[]).map(folder=>({...folder}))};}
function projectSignature(project){return JSON.stringify({name:project.name,width:project.width,height:project.height,folders:(project.folders||[]).map(({id,name,parentId,order,visible,expanded,opacity,blendMode})=>({id,name,parentId,order,visible,expanded,opacity,blendMode})),layers:project.layers.map(({id,name,x,y,width,height,original_width,original_height,rotation,opacity,visible,z_index,type,text,blendMode,parentId,order})=>({id,name,x,y,width,height,original_width,original_height,rotation,opacity,visible,z_index,type,text,blendMode,parentId,order}))});}
function historyFor(project){if(!state.histories.has(project.id))state.histories.set(project.id,{entries:[],index:-1});return state.histories.get(project.id);}
function historyIcon(label){if(/move|align/i.test(label))return 'tools-move';if(/rotate/i.test(label))return 'rotate';if(/transform|resize|opacity|aspect/i.test(label))return 'tools-transform';if(/paste|layer|new|text/i.test(label))return 'lrs-newlayer';if(/open/i.test(label))return 'pix_layer';return 'panels-history';}
function initializeHistory(project,label,clean=false){state.histories.set(project.id,{entries:[{label,icon:historyIcon(label),snapshot:projectSnapshot(project)}],index:0});state.savedSignatures.set(project.id,clean?projectSignature(project):null);refreshDirty(project);}
function recordProjectHistory(project,label){const history=historyFor(project);if(history.index<history.entries.length-1)history.entries.splice(history.index+1);history.entries.push({label,icon:historyIcon(label),snapshot:projectSnapshot(project)});if(history.entries.length>100)history.entries.shift();history.index=history.entries.length-1;refreshDirty(project);if(project.id===state.activeProjectId)renderHistory();}
function recordHistory(label){const project=activeProject();if(project)recordProjectHistory(project,label);}
function restoreHistoryTo(index){const project=activeProject();if(!project)return;const history=historyFor(project);if(index<0||index>=history.entries.length||index===history.index)return;history.index=index;const snapshot=history.entries[index].snapshot;project.name=snapshot.name;project.width=snapshot.width??project.width;project.height=snapshot.height??project.height;project.layers=snapshot.layers.map(layer=>({...layer,textData:clonePlain(layer.textData)}));project.folders=(snapshot.folders||[]).map(folder=>({...folder}));normalizeProjectTree(project);state.selectedLayerIds=new Set([...state.selectedLayerIds].filter(id=>project.layers.some(layer=>layer.id===id)));state.selectedFolderIds=new Set([...state.selectedFolderIds].filter(id=>project.folders.some(folder=>folder.id===id)));if(!project.layers.some(layer=>layer.id===state.activeLayerId)&&!project.folders.some(folder=>folder.id===state.activeFolderId))selectOnlyLayer(topLayer(project)?.id||null);refreshDirty(project);render();}function restoreHistory(direction){const project=activeProject();if(project)restoreHistoryTo(historyFor(project).index+direction);}
function refreshDirty(project){const dirty=projectSignature(project)!==state.savedSignatures.get(project.id);state.dirtyProjects[dirty?'add':'delete'](project.id);updateSaveUi();}
function updateSaveUi(){const project=activeProject(),status=document.getElementById('saveStatus'),button=document.getElementById('saveButton');if(!project){status.textContent='No document';button.hidden=true;return;}status.textContent=state.busy?'Working locally…':state.dirtyProjects.has(project.id)?'Unsaved changes':'Saved locally';button.hidden=!state.dirtyProjects.has(project.id);button.disabled=state.busy;}

function treeItemParent(item){return item.parentId||null;}
function treeChildren(project,parentId=null){
    const parent=parentId||null,folders=(project.folders||[]).filter(folder=>treeItemParent(folder)===parent).map(folder=>({kind:'folder',item:folder})),layers=project.layers.filter(layer=>treeItemParent(layer)===parent).map(layer=>({kind:'layer',item:layer}));
    return [...folders,...layers].sort((a,b)=>{const aOrder=Number(a.item.order),bOrder=Number(b.item.order),aHas=Number.isFinite(aOrder),bHas=Number.isFinite(bOrder);if(aHas&&bHas&&aOrder!==bOrder)return aOrder-bOrder;if(aHas!==bHas)return aHas?-1:1;if(a.kind!==b.kind)return a.kind==='folder'?-1:1;return Number(b.item.z_index||0)-Number(a.item.z_index||0);});
}
function normalizeProjectTree(project){
    project.folders=project.folders||[];const folderIds=new Set(project.folders.map(folder=>folder.id));project.folders.forEach(folder=>{if(folder.parentId&&!folderIds.has(folder.parentId))folder.parentId=null;});project.layers.forEach(layer=>{if(layer.parentId&&!folderIds.has(layer.parentId))layer.parentId=null;});
    const leaves=[],visited=new Set();const walk=(parentId=null,ancestors=new Set())=>{treeChildren(project,parentId).forEach(({kind,item},order)=>{item.order=order;if(kind==='folder'){if(ancestors.has(item.id))return;visited.add(item.id);walk(item.id,new Set([...ancestors,item.id]));}else leaves.push(item);});};walk();
    project.folders.filter(folder=>!visited.has(folder.id)).forEach(folder=>folder.parentId=null);if(project.folders.some(folder=>!visited.has(folder.id))){visited.clear();leaves.length=0;walk();}
    leaves.forEach((layer,index)=>layer.z_index=leaves.length-1-index);return project;
}
function folderAncestors(project,parentId){const result=[];let current=parentId;while(current){const folder=(project.folders||[]).find(item=>item.id===current);if(!folder||result.includes(folder))break;result.push(folder);current=folder.parentId;}return result;}
function layerIsVisible(project,layer){return layer.visible&&folderAncestors(project,layer.parentId).every(folder=>folder.visible);}
function effectiveLayerOpacity(project,layer){return folderAncestors(project,layer.parentId).reduce((opacity,folder)=>opacity*(Number(folder.opacity??100)/100),Number(layer.opacity)/100);}
function panelTreeRows(project,parentId=null,depth=0,result=[]){treeChildren(project,parentId).forEach(node=>{result.push({...node,depth});if(node.kind==='folder'&&node.item.expanded!==false)panelTreeRows(project,node.item.id,depth+1,result);});return result;}
function findTreeNode(project,kind,id){const collection=kind==='folder'?(project.folders||[]):project.layers;const item=collection.find(candidate=>candidate.id===id);return item?{kind,item}:null;}
function folderContains(project,folderId,candidateId){let current=(project.folders||[]).find(folder=>folder.id===candidateId);while(current){if(current.parentId===folderId)return true;current=(project.folders||[]).find(folder=>folder.id===current.parentId);}return false;}
function newLayer(project,{name='Layer',dataUrl,x=0,y=0,width,height,rotation=0,opacity=100,visible=true,z_index,type='pixel',text=null,textData=null,blendMode='normal',parentId=null,order=null}){
    return {id:nextLayerId(),name,image_url:dataUrl,x:Number(x),y:Number(y),width:Number(width),height:Number(height),original_width:Number(width),original_height:Number(height),rotation:Number(rotation),opacity:Number(opacity),visible:Boolean(visible),z_index:z_index??project.layers.length,type,text,textData:clonePlain(textData),text_origin_x:Number(x),text_origin_y:Number(y),blendMode,parentId,order};
}

function createLocalProject({name,width,height,layers=[],folders=[],historyLabel='New',clean=false}){
    const project={id:nextProjectId(),name,width:Number(width),height:Number(height),layers,folders};normalizeProjectTree(project);
    state.projects.set(project.id,project);state.tabs.push(project.id);state.activeProjectId=project.id;selectOnlyLayer(topLayer(project)?.id||null);state.zooms.set(project.id,1);state.zoom=1;initializeHistory(project,historyLabel,clean);render();requestAnimationFrame(fitScreen);return project;
}

function canvasToDataUrl(canvas){return canvas.toDataURL('image/png');}
function transparentCanvas(width,height){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));return canvas;}
async function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Could not decode a local layer image.'));image.src=src;});}
async function imageFileToPng(file){const bitmap=await createImageBitmap(file);if(bitmap.width>8192||bitmap.height>8192){bitmap.close();throw new Error('Images are limited to 8192 × 8192 pixels.');}const canvas=transparentCanvas(bitmap.width,bitmap.height);canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();return {dataUrl:canvasToDataUrl(canvas),width:canvas.width,height:canvas.height};}

function countPsdLayers(children=[]){return children.reduce((count,layer)=>count+(layer.children?countPsdLayers(layer.children):1),0);}
function importPsdTree(children,project,parentId=null){
    (children||[]).forEach((source,order)=>{
        if(Array.isArray(source.children)){
            const folder={id:nextFolderId(),name:source.name||'Group',parentId,order,visible:!Boolean(source.hidden),expanded:source.opened!==false,opacity:Math.round((source.opacity??1)*100),blendMode:source.blendMode||'pass through'};project.folders.push(folder);importPsdTree(source.children,project,folder.id);return;
        }
        const canvas=source.canvas||('text' in source?renderTextCanvas(source.text):transparentCanvas(Math.max(1,(source.right||1)-(source.left||0)),Math.max(1,(source.bottom||1)-(source.top||0))));
        const x=Number(source.left)||0,y=Number(source.top)||0,layer=newLayer(project,{name:source.name||'Layer',dataUrl:canvasToDataUrl(canvas),x,y,width:canvas.width,height:canvas.height,opacity:Math.round((source.opacity??1)*100),visible:!Boolean(source.hidden),type:source.text?'text':'pixel',text:source.text?.text||null,textData:source.text||null,blendMode:source.blendMode||'normal',parentId,order});
        layer.text_origin_x=x;layer.text_origin_y=y;project.layers.push(layer);
    });
}const cssBlendModes={normal:'normal',dissolve:'normal',darken:'darken',multiply:'multiply','color burn':'color-burn','linear burn':'multiply','darker color':'darken',lighten:'lighten',screen:'screen','color dodge':'color-dodge','linear dodge':'plus-lighter','lighter color':'lighten',overlay:'overlay','soft light':'soft-light','hard light':'hard-light','vivid light':'hard-light','linear light':'hard-light','pin light':'hard-light','hard mix':'hard-light',difference:'difference',exclusion:'exclusion',subtract:'difference',divide:'exclusion',hue:'hue',saturation:'saturation',color:'color',luminosity:'luminosity'};
function cssBlendMode(mode){return cssBlendModes[mode]||'normal';}
function canvasBlendMode(mode){const value=cssBlendMode(mode);return value==='plus-lighter'?'lighter':value;}
function colorCss(color){if(!color)return '#000000';const channel=value=>Math.max(0,Math.min(255,Math.round(Number(value)||0)));return `rgb(${channel(color.r)},${channel(color.g)},${channel(color.b)})`;}
function renderTextCanvas(textData){const text=String(textData?.text||'Text');const fontSize=Math.max(1,Number(textData?.style?.fontSize)||36);const lines=text.split(/\r?\n/);const probe=transparentCanvas(1,1),ctx=probe.getContext('2d');ctx.font=`${fontSize}px Arial`;const width=Math.max(2,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line||' ').width))+8));const lineHeight=Math.ceil(fontSize*1.25),height=Math.max(2,lineHeight*lines.length+6);const canvas=transparentCanvas(width,height),draw=canvas.getContext('2d');draw.font=`${fontSize}px Arial`;draw.textBaseline='top';draw.fillStyle=colorCss(textData?.style?.fillColor);lines.forEach((line,index)=>draw.fillText(line,4,3+index*lineHeight));return canvas;}

async function openPsdFile(file){
    const buffer=await file.arrayBuffer();
    const structure=readPsd(buffer,{skipLayerImageData:true,skipCompositeImageData:true,skipThumbnail:true});
    if(structure.width>8192||structure.height>8192)throw new Error('PSD documents are limited to 8192 × 8192 pixels.');
    if(countPsdLayers(structure.children)>500)throw new Error('PSD documents are limited to 500 layers.');
    const psd=readPsd(buffer,{skipThumbnail:true});
    const project={id:nextProjectId(),name:file.name.replace(/\.psd$/i,''),width:psd.width,height:psd.height,layers:[],folders:[]};
    importPsdTree(psd.children,project);normalizeProjectTree(project);
    if(!project.layers.length&&psd.canvas){project.layers.push(newLayer(project,{name:'Background',dataUrl:canvasToDataUrl(psd.canvas),width:psd.canvas.width,height:psd.canvas.height,z_index:0,order:0}));}
    return createLocalProject({...project,historyLabel:'Open PSD',clean:true});
}
async function openRasterFile(file){const png=await imageFileToPng(file);const project={id:nextProjectId(),name:file.name.replace(/\.[^.]+$/,''),width:png.width,height:png.height,layers:[]};project.layers.push(newLayer(project,{name:file.name,dataUrl:png.dataUrl,width:png.width,height:png.height,z_index:0}));return createLocalProject({...project,historyLabel:'Open Image',clean:false});}
async function openLocalFile(file){state.loadingFile={name:file.name};switchPanel('layers');renderLayers();setBusy(true);try{return file.name.toLowerCase().endsWith('.psd')?await openPsdFile(file):await openRasterFile(file);}finally{state.loadingFile=null;setBusy(false);renderLayers();}}

async function placeImageFile(file){const project=activeProject();if(!project)throw new Error('Open a document before placing an image.');const png=await imageFileToPng(file),x=(project.width-png.width)/2,y=(project.height-png.height)/2;return addLayer(project,png.dataUrl,png.width,png.height,file.name,x,y,'Place Image');}
async function placeLocalImage(file){state.loadingFile={name:file.name,status:'Placing at original size…'};switchPanel('layers');renderLayers();setBusy(true);try{return await placeImageFile(file);}finally{state.loadingFile=null;setBusy(false);renderLayers();}}
async function layerCanvasForExport(layer){
    const image=await loadImage(layer.image_url),width=Math.max(1,Math.round(layer.width)),height=Math.max(1,Math.round(layer.height)),angle=Number(layer.rotation)||0;
    if(!angle){const canvas=transparentCanvas(width,height);canvas.getContext('2d').drawImage(image,0,0,width,height);return {canvas,left:Math.round(layer.x),top:Math.round(layer.y)};}
    const radians=angle*Math.PI/180,cos=Math.abs(Math.cos(radians)),sin=Math.abs(Math.sin(radians)),boxWidth=Math.max(1,Math.ceil(width*cos+height*sin)),boxHeight=Math.max(1,Math.ceil(width*sin+height*cos));
    const canvas=transparentCanvas(boxWidth,boxHeight),ctx=canvas.getContext('2d');ctx.translate(boxWidth/2,boxHeight/2);ctx.rotate(radians);ctx.drawImage(image,-width/2,-height/2,width,height);
    return {canvas,left:Math.round(layer.x-(boxWidth-width)/2),top:Math.round(layer.y-(boxHeight-height)/2)};
}
function exportTextData(layer){const text=clonePlain(layer.textData)||{text:layer.text||'Text',style:{font:{name:'ArialMT'},fontSize:36,fillColor:{r:0,g:0,b:0}}};text.text=layer.text||text.text||'Text';const transform=Array.isArray(text.transform)&&text.transform.length>=6?[...text.transform]:[1,0,0,1,layer.x,layer.y+(Number(text.style?.fontSize)||36)];transform[4]+=layer.x-(layer.text_origin_x??layer.x);transform[5]+=layer.y-(layer.text_origin_y??layer.y);text.transform=transform;return text;}
async function renderComposite(project,layers=project.layers){const canvas=transparentCanvas(project.width,project.height),ctx=canvas.getContext('2d');for(const layer of [...layers].sort((a,b)=>a.z_index-b.z_index)){if(!layerIsVisible(project,layer))continue;const image=await loadImage(layer.image_url);ctx.save();ctx.globalAlpha=effectiveLayerOpacity(project,layer);ctx.globalCompositeOperation=canvasBlendMode(layer.blendMode);ctx.translate(layer.x+layer.width/2,layer.y+layer.height/2);ctx.rotate(layer.rotation*Math.PI/180);ctx.drawImage(image,-layer.width/2,-layer.height/2,layer.width,layer.height);ctx.restore();}return canvas;}
function canvasToBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not prepare the selected layers.')),'image/png'));}
function updateLayerizeProgress(){document.getElementById('layerizeProgress').hidden=state.layerizeRunning===0;}
function wait(milliseconds){return new Promise(resolve=>setTimeout(resolve,milliseconds));}
async function responseJson(response){const data=await response.json().catch(()=>({}));if(!response.ok||data.success===false)throw new Error(data.message||data.error||`Layerize request failed (HTTP ${response.status}).`);return data;}
async function startLayerize(){
    const project=activeProject(),layers=selectedLayers();if(!project||!layers.length){toast('Select one or more layers first.');return;}
    const context={projectId:project.id,layerIds:layers.map(layer=>layer.id)};state.layerizeRunning+=1;updateLayerizeProgress();
    try{
        const canvas=await renderComposite(project,layers),blob=await canvasToBlob(canvas),form=new FormData();form.append('image',blob,`${project.name||'document'}-selection.png`);
        const queued=await responseJson(await fetch(layerizeConfig.storeUrl,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':layerizeConfig.csrfToken},body:form}));
        toast(`Layerize job #${queued.id} queued.`);await pollLayerizeJob(queued.statusUrl,context);
    }catch(error){toast(error.message||'Layerize failed.');}
    finally{state.layerizeRunning=Math.max(0,state.layerizeRunning-1);updateLayerizeProgress();}
}
async function pollLayerizeJob(statusUrl,context){
    for(let attempt=0;attempt<400;attempt+=1){const job=await responseJson(await fetch(statusUrl,{headers:{Accept:'application/json'},cache:'no-store'}));if(job.status==='ready'){const project=state.projects.get(context.projectId);if(project){await importLayerizeResult(project,job,context.layerIds);toast(`Layerize job #${job.id} added ${job.layers.length} layers.`);}else toast(`Layerize job #${job.id} is ready in Layerize History.`);return;}if(job.status==='failed')throw new Error(job.error||'Layerize failed.');await wait(3000);}throw new Error('Layerize is still processing. Open Layerize History to check it later.');
}
function validLayerizeBounds(bounds){return Array.isArray(bounds)&&bounds.length===4&&bounds.map(Number).every(Number.isFinite)&&Number(bounds[2])>Number(bounds[0])&&Number(bounds[3])>Number(bounds[1]);}
async function loadLayerizeImage(item){const response=await fetch(item.url,{headers:{Accept:'image/*'}});if(!response.ok)throw new Error(`Could not download ${item.name||'a generated layer'}.`);return {...item,png:await imageFileToPng(await response.blob())};}
async function importLayerizeResult(project,job,anchorIds=[]){
    if(!Array.isArray(job.layers)||!job.layers.length)throw new Error('This Layerize job has no layers to import.');
    const loaded=[];for(const item of [...job.layers].sort((a,b)=>Number(b.zIndex)-Number(a.zIndex)))loaded.push(await loadLayerizeImage(item));
    const base=loaded.find(item=>Number(item.zIndex)===0)||loaded.at(-1)||loaded[0],sourceWidth=Number(base.width)||base.png.width,sourceHeight=Number(base.height)||base.png.height,scaleX=project.width/sourceWidth,scaleY=project.height/sourceHeight;
    const anchored=project.layers.filter(layer=>anchorIds.includes(layer.id)),topAnchor=anchored.reduce((top,layer)=>!top||layer.z_index>top.z_index?layer:top,null),sameParent=anchored.length&&anchored.every(layer=>treeItemParent(layer)===treeItemParent(anchored[0])),parentId=sameParent?treeItemParent(anchored[0]):null,siblings=treeChildren(project,parentId);let insertAt=topAnchor?siblings.findIndex(node=>node.kind==='layer'&&node.item.id===topAnchor.id):0;if(insertAt<0)insertAt=0;siblings.forEach((node,index)=>node.item.order=index>=insertAt?index+1:index);
    const folder={id:nextFolderId(),name:`Layerize #${job.id}`,parentId,order:insertAt,visible:true,expanded:true,opacity:100,blendMode:'pass through'};project.folders.push(folder);
    const imported=[];loaded.forEach((item,index)=>{const bounds=validLayerizeBounds(item.bounds)?item.bounds.map(Number):null,isFullDocument=item.png.width===sourceWidth&&item.png.height===sourceHeight;let x=0,y=0,width=project.width,height=project.height;if(bounds&&!isFullDocument&&Number(item.zIndex)!==0){x=bounds[0]*scaleX;y=bounds[1]*scaleY;width=(bounds[2]-bounds[0])*scaleX;height=(bounds[3]-bounds[1])*scaleY;}const layer=newLayer(project,{name:`Layerize · ${item.name||`Layer ${index+1}`}`,dataUrl:item.png.dataUrl,x,y,width,height,parentId:folder.id,order:index});project.layers.push(layer);imported.push(layer);});
    normalizeProjectTree(project);recordProjectHistory(project,`Import Layerize #${job.id}`);if(project.id===state.activeProjectId){selectOnlyFolder(folder.id);switchPanel('layers');render();}else renderTabs();
}async function showLayerizeHistory(){const dialog=document.getElementById('layerizeHistoryDialog'),list=document.getElementById('layerizeHistoryList');list.innerHTML='<div class="ps-panel-empty">Loading Layerize history…</div>';dialog.showModal();try{const data=await responseJson(await fetch(layerizeConfig.historyUrl,{headers:{Accept:'application/json'},cache:'no-store'}));renderLayerizeHistory(data.jobs||[]);}catch(error){list.innerHTML=`<div class="ps-panel-empty">${escapeHtml(error.message)}</div>`;}}
function renderLayerizeHistory(jobs){const list=document.getElementById('layerizeHistoryList');list.replaceChildren();if(!jobs.length){list.innerHTML='<div class="ps-panel-empty">No Layerize jobs yet.</div>';return;}jobs.forEach(job=>{const card=document.createElement('article');card.className='ps-layerize-job';const image=document.createElement('img');image.alt=`Layerize job ${job.id}`;if(job.previewUrl)image.src=job.previewUrl;const body=document.createElement('div');body.className='ps-layerize-job-body';const meta=document.createElement('div');meta.className='ps-layerize-job-meta';const name=document.createElement('strong');name.textContent=`Job #${job.id}`;const status=document.createElement('span');status.className=`ps-layerize-job-status ${job.status}`;status.textContent=job.status;meta.append(name,status);const date=document.createElement('span');date.textContent=job.createdAt?new Date(job.createdAt).toLocaleString():'';const button=document.createElement('button');button.type='button';button.textContent=job.status==='ready'?`Import ${job.layers.length} layers`:job.status==='failed'?'Failed':'Processing…';button.disabled=job.status!=='ready';button.addEventListener('click',async()=>{const project=activeProject();if(!project){toast('Open a document before importing Layerize history.');return;}button.disabled=true;button.textContent='Importing…';try{await importLayerizeResult(project,job,selectedLayers().map(layer=>layer.id));document.getElementById('layerizeHistoryDialog').close();toast(`Imported Layerize job #${job.id}.`);}catch(error){toast(error.message);button.disabled=false;button.textContent=`Import ${job.layers.length} layers`;}});body.append(meta,date);if(job.error){const error=document.createElement('span');error.className='ps-layerize-error';error.textContent=job.error;body.append(error);}body.append(button);card.append(image,body);list.append(card);});}
async function psdChildrenFor(project,parentId=null){
    const children=[];
    for(const {kind,item} of treeChildren(project,parentId)){
        if(kind==='folder'){
            const group={name:item.name,children:await psdChildrenFor(project,item.id),opened:item.expanded!==false,hidden:!item.visible,opacity:Number(item.opacity??100)/100};if(item.blendMode)group.blendMode=item.blendMode;children.push(group);continue;
        }
        const rendered=await layerCanvasForExport(item),child={name:item.name,left:rendered.left,top:rendered.top,canvas:rendered.canvas,opacity:item.opacity/100,hidden:!item.visible,blendMode:item.blendMode||'normal'};if(item.type==='text')child.text=exportTextData(item);children.push(child);
    }
    return children;
}
async function exportActiveProjectAsPsd(){
    const project=activeProject();if(!project||state.busy)return;setBusy(true);
    try{
        normalizeProjectTree(project);const children=await psdChildrenFor(project);
        const psd={width:project.width,height:project.height,children,canvas:await renderComposite(project)};
        const buffer=writePsd(psd,{generateThumbnail:true,invalidateTextLayers:true});
        const blob=new Blob([buffer],{type:'image/vnd.adobe.photoshop'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${project.name.replace(/[\\/:*?"<>|]+/g,'_')||'Untitled'}.psd`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
        state.savedSignatures.set(project.id,projectSignature(project));state.dirtyProjects.delete(project.id);updateSaveUi();toast(`Downloaded ${link.download}.`);
    }catch(error){toast(error.message||'Could not create the PSD file.');}finally{setBusy(false);}
}
function thumbnailForLayer(layer){
    const source=layer.image_url;if(!state.thumbnailCache.has(source))state.thumbnailCache.set(source,(async()=>{const image=await loadImage(source),scale=Math.min(1,34/image.naturalWidth,34/image.naturalHeight),canvas=transparentCanvas(Math.max(1,Math.round(image.naturalWidth*scale)),Math.max(1,Math.round(image.naturalHeight*scale)));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvasToDataUrl(canvas);})().catch(error=>{state.thumbnailCache.delete(source);throw error;}));return state.thumbnailCache.get(source);
}
function layerImage(layer,role){
    const key=`${role}:${layer.id}`;let image=state.imageElements.get(key);if(!image){image=new Image();image.draggable=false;state.imageElements.set(key,image);if(role==='canvas')image.addEventListener('pointerdown',()=>{if(state.tool==='move'&&document.getElementById('autoSelect').checked){selectOnlyLayer(image.dataset.layerId);renderLayers();renderProperties();updateMoveable();}});}
    image.className=role==='canvas'?'ps-canvas-layer':'ps-layer-thumb';image.dataset.layerId=layer.id;image.alt=layer.name;
    if(state.imageSources.get(key)!==layer.image_url){const source=layer.image_url;state.imageSources.set(key,source);if(role==='canvas')image.src=source;else{const scale=Math.min(1,31/Math.max(1,layer.width),31/Math.max(1,layer.height));image.style.width=`${Math.max(1,Math.round(layer.width*scale))}px`;image.style.height=`${Math.max(1,Math.round(layer.height*scale))}px`;image.removeAttribute('src');thumbnailForLayer(layer).then(url=>{if(state.imageSources.get(key)===source)image.src=url;}).catch(()=>{});}}
    return image;
}function render(){renderTabs();renderCanvas();renderLayers();if(state.panel==='properties')renderProperties();if(state.panel==='history')renderHistory();updateSaveUi();}
function renderTabs(){const tabs=document.getElementById('documentTabs');tabs.replaceChildren();state.tabs.forEach(id=>{const project=state.projects.get(id),tab=document.createElement('button');tab.type='button';tab.className=`ps-tab${id===state.activeProjectId?' active':''}`;tab.innerHTML=`<span class="ps-tab-name">${escapeHtml(project.name)}${state.dirtyProjects.has(id)?' *':''} @ ${Math.round((state.zooms.get(id)||1)*100)}% (RGB/8)</span><span class="ps-tab-close" aria-label="Close">${iconMarkup('cross')}</span>`;tab.addEventListener('click',event=>{if(event.target.closest('.ps-tab-close'))closeTab(id);else{state.activeProjectId=id;state.zoom=state.zooms.get(id)||1;selectOnlyLayer(topLayer(project)?.id||null);clearSelection();render();}});tabs.append(tab);});}
function renderCanvas(){state.moveable?.destroy();state.moveable=null;const project=activeProject(),canvas=document.getElementById('canvas'),shell=document.getElementById('canvasShell'),empty=document.getElementById('emptyState');canvas.querySelectorAll('.ps-canvas-layer').forEach(element=>element.remove());empty.hidden=!!project;shell.hidden=!project;if(!project)return;canvas.style.width=`${project.width*state.zoom}px`;canvas.style.height=`${project.height*state.zoom}px`;[...project.layers].sort((a,b)=>a.z_index-b.z_index).forEach(layer=>{const image=layerImage(layer,'canvas');Object.assign(image.style,{left:`${layer.x*state.zoom}px`,top:`${layer.y*state.zoom}px`,width:`${layer.width*state.zoom}px`,height:`${layer.height*state.zoom}px`,opacity:String(effectiveLayerOpacity(project,layer)),display:layerIsVisible(project,layer)?'block':'none',zIndex:String(layer.z_index),mixBlendMode:cssBlendMode(layer.blendMode),transform:`rotate(${layer.rotation}deg)`});canvas.append(image);});renderSelection();requestAnimationFrame(updateMoveable);}
function syncLayerControls(){const layer=activeLayer(),blend=document.getElementById('layerBlendMode'),opacity=document.getElementById('layerOpacity'),slider=document.getElementById('layerOpacitySlider');blend.disabled=!layer;opacity.disabled=!layer;slider.disabled=!layer;if(layer){blend.value=layer.blendMode||'normal';opacity.value=layer.opacity;slider.value=layer.opacity;}}
function clearLayerDragState(panel){panel.querySelectorAll('.drag-before,.drag-after,.drag-inside').forEach(item=>item.classList.remove('drag-before','drag-after','drag-inside'));}
function syncLayerRowSelection(panel){panel.querySelectorAll('.ps-layer-row[data-item-id]').forEach(row=>{const folder=row.dataset.itemKind==='folder',id=row.dataset.itemId;row.classList.toggle('selected',folder?state.selectedFolderIds.has(id):state.selectedLayerIds.has(id));row.classList.toggle('active',folder?id===state.activeFolderId:id===state.activeLayerId);});syncLayerControls();}
function moveTreeItem(project,dragKind,dragId,targetKind,targetId,placement){
    const dragged=findTreeNode(project,dragKind,dragId),target=findTreeNode(project,targetKind,targetId);if(!dragged||!target||(dragKind===targetKind&&dragId===targetId))return;
    const destinationParent=placement==='inside'&&targetKind==='folder'?targetId:treeItemParent(target.item);if(dragKind==='folder'&&(destinationParent===dragId||folderContains(project,dragId,destinationParent)))return;dragged.item.parentId=destinationParent;
    const siblings=treeChildren(project,destinationParent).filter(node=>!(node.kind===dragKind&&node.item.id===dragId));let index=placement==='inside'?0:siblings.findIndex(node=>node.kind===targetKind&&node.item.id===targetId);if(index<0)index=siblings.length;else if(placement==='after')index+=1;siblings.splice(index,0,dragged);siblings.forEach((node,order)=>node.item.order=order);normalizeProjectTree(project);
    if(dragKind==='folder')selectOnlyFolder(dragId);else selectOnlyLayer(dragId);recordHistory(dragKind==='folder'?'Move Group':'Reorder Layers');render();
}
function beginItemRename(item,label,row,historyLabel){const input=document.createElement('input');input.className='ps-layer-name-input';input.value=item.name;label.replaceWith(input);row.draggable=false;input.focus();input.select();let finished=false;const finish=commit=>{if(finished)return;finished=true;const name=input.value.trim();if(commit&&name&&name!==item.name){item.name=name;recordHistory(historyLabel);render();}else renderLayers();};input.addEventListener('click',event=>event.stopPropagation());input.addEventListener('dblclick',event=>event.stopPropagation());input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();finish(true);}if(event.key==='Escape'){event.preventDefault();finish(false);}});input.addEventListener('blur',()=>finish(true));}
function bindTreeDrag(row,node,panel){
    row.addEventListener('dragstart',event=>{if(node.kind==='folder')selectOnlyFolder(node.item.id);else if(!state.selectedLayerIds.has(node.item.id))selectOnlyLayer(node.item.id);else state.activeLayerId=node.item.id;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-ps-layer',`${node.kind}:${node.item.id}`);row.classList.add('dragging');});
    row.addEventListener('dragend',()=>{row.classList.remove('dragging');clearLayerDragState(panel);});
    row.addEventListener('dragover',event=>{event.preventDefault();const ratio=(event.clientY-row.getBoundingClientRect().top)/row.offsetHeight,placement=node.kind==='folder'&&ratio>=.25&&ratio<=.75?'inside':ratio>.5?'after':'before';clearLayerDragState(panel);row.classList.add(`drag-${placement}`);event.dataTransfer.dropEffect='move';});
    row.addEventListener('dragleave',event=>{if(!row.contains(event.relatedTarget))row.classList.remove('drag-before','drag-after','drag-inside');});
    row.addEventListener('drop',event=>{event.preventDefault();const [dragKind,dragId]=(event.dataTransfer.getData('application/x-ps-layer')||'').split(':');const ratio=(event.clientY-row.getBoundingClientRect().top)/row.offsetHeight,placement=node.kind==='folder'&&ratio>=.25&&ratio<=.75?'inside':ratio>.5?'after':'before';clearLayerDragState(panel);moveTreeItem(activeProject(),dragKind,dragId,node.kind,node.item.id,placement);});
}
function renderLayers(){
    const panel=document.getElementById('layersPanel'),project=activeProject();panel.replaceChildren();
    if(state.loadingFile){const row=document.createElement('div');row.className='ps-layer-row ps-layer-uploading';row.innerHTML=`<span></span><span class="ps-layer-spinner"></span><span class="ps-layer-name"><strong>${escapeHtml(state.loadingFile.name)}</strong><small>${escapeHtml(state.loadingFile.status||'Opening locally…')}</small></span>`;panel.append(row);}
    if(!project){syncLayerControls();return;}
    const rows=panelTreeRows(project),orderedLayers=rows.filter(row=>row.kind==='layer').map(row=>row.item);
    rows.forEach(node=>{
        const item=node.item,row=document.createElement('div'),selected=node.kind==='folder'?state.selectedFolderIds.has(item.id):state.selectedLayerIds.has(item.id),active=node.kind==='folder'?item.id===state.activeFolderId:item.id===state.activeLayerId;row.className=`ps-layer-row ps-layer-${node.kind}-row${selected?' selected':''}${active?' active':''}`;row.draggable=true;row.dataset.itemKind=node.kind;row.dataset.itemId=item.id;row.style.setProperty('--layer-depth',node.depth);row.style.gridTemplateColumns=`28px ${38+node.depth*14}px minmax(0,1fr)`;
        if(node.kind==='folder'){
            row.innerHTML=`<button type="button" class="ps-layer-eye${item.visible?'':' hidden-layer'}" title="${item.visible?'Hide':'Show'} group">${iconMarkup('lrs-eye')}</button><span class="ps-layer-folder-thumb"><button type="button" class="ps-folder-toggle" title="${item.expanded===false?'Expand':'Collapse'} group">${iconMarkup(item.expanded===false?'lrs-arrow_right':'lrs-arrow_down')}</button>${iconMarkup(item.expanded===false?'lrs-folder':'lrs-vfolder')}</span><span class="ps-layer-name"><strong>${escapeHtml(item.name)}</strong><small>Layer Group</small></span>`;
            row.querySelector('.ps-folder-toggle').addEventListener('click',event=>{event.stopPropagation();item.expanded=item.expanded===false;refreshDirty(project);renderLayers();});
            row.addEventListener('click',event=>{if(event.target.closest('.ps-layer-eye')){item.visible=!item.visible;recordHistory(item.visible?'Show Group':'Hide Group');render();}else if(!event.target.closest('.ps-folder-toggle,.ps-layer-name-input')){selectOnlyFolder(item.id);syncLayerRowSelection(panel);renderProperties();updateMoveable();}});
            row.querySelector('.ps-layer-name strong').addEventListener('dblclick',event=>{event.preventDefault();event.stopPropagation();beginItemRename(item,event.currentTarget,row,'Rename Group');});
        }else{
            row.innerHTML=`<button type="button" class="ps-layer-eye${item.visible?'':' hidden-layer'}" title="${item.visible?'Hide':'Show'} layer">${iconMarkup('lrs-eye')}</button><span class="ps-layer-name"><strong>${escapeHtml(item.name)}</strong><small>${item.type==='text'?'Text Layer':'Pixel Layer'}</small></span>`;row.insertBefore(layerImage(item,'layers'),row.lastElementChild);
            row.querySelector('.ps-layer-name strong').addEventListener('dblclick',event=>{event.preventDefault();event.stopPropagation();beginItemRename(item,event.currentTarget,row,'Rename Layer');});
            row.addEventListener('click',event=>{if(event.target.closest('.ps-layer-eye')){item.visible=!item.visible;recordHistory(item.visible?'Show Layer':'Hide Layer');render();}else if(!event.target.closest('.ps-layer-name-input')){selectLayerFromPanel(event,item,orderedLayers);syncLayerRowSelection(panel);renderProperties();updateMoveable();}});
        }
        bindTreeDrag(row,node,panel);panel.append(row);
    });
    syncLayerControls();
}
function switchPanel(panel){state.panel=panel;document.querySelectorAll('[data-panel-tab]').forEach(button=>button.classList.toggle('active',button.dataset.panelTab===panel));document.querySelectorAll('[data-panel-view]').forEach(view=>view.classList.toggle('active',view.dataset.panelView===panel));if(panel==='properties')renderProperties();if(panel==='history')renderHistory();}
function renderProperties(){if(state.panel!=='properties')return;const panel=document.getElementById('propertiesPanel'),layer=activeLayer();if(!layer){panel.innerHTML='<div class="ps-panel-empty">Select a layer to view its properties.</div>';return;}const typeIcon=layer.type==='text'?'tools-htype':'pix_layer',typeLabel=layer.type==='text'?'Text Layer':'Pixel Layer';panel.innerHTML=`<div class="ps-property-identity"><span data-property-thumb></span><strong>${escapeHtml(layer.name)}<small>${iconMarkup(typeIcon)} ${typeLabel}</small></strong></div><section class="ps-property-section"><h3>${iconMarkup('lrs-arrow_down')} Transform</h3><div class="ps-property-grid"><label>W<input data-layer-property="width" type="number" min="1" value="${Math.round(layer.width)}"></label><label>X<input data-layer-property="x" type="number" value="${Math.round(layer.x)}"></label><label>H<input data-layer-property="height" type="number" min="1" value="${Math.round(layer.height)}"></label><label>Y<input data-layer-property="y" type="number" value="${Math.round(layer.y)}"></label><label>°<input data-layer-property="rotation" type="number" step="0.1" value="${Number(layer.rotation).toFixed(1)}"></label><label>%<input data-layer-property="opacity" type="number" min="0" max="100" value="${layer.opacity}"></label></div></section><section class="ps-property-section"><h3>${iconMarkup('lrs-arrow_down')} Align and Distribute</h3><div class="ps-align-buttons"><button type="button" data-align-layer="left">${iconMarkup('align-h0')}</button><button type="button" data-align-layer="center">${iconMarkup('align-h1')}</button><button type="button" data-align-layer="right">${iconMarkup('align-h2')}</button></div><button type="button" class="ps-restore-ratio" data-action="restoreAspectRatio">${iconMarkup('reload')}<span>Restore aspect ratio</span></button></section>`;panel.querySelector('[data-property-thumb]').replaceWith(layerImage(layer,'properties'));}
function renderHistory(){if(state.panel!=='history')return;const panel=document.getElementById('historyPanel'),project=activeProject();if(!project){panel.innerHTML='<div class="ps-panel-empty">Open a document to see its history.</div>';return;}const history=historyFor(project);panel.innerHTML=`<div class="ps-history-document"><span class="ps-history-icon">${iconMarkup('pix_layer')}</span><strong>${escapeHtml(project.name)}</strong></div><ol class="ps-history-list">${history.entries.map((entry,index)=>`<li class="ps-history-entry${index===history.index?' current':''}${index>history.index?' future':''}"><button type="button" data-history-index="${index}"><span class="ps-history-icon">${iconMarkup(entry.icon)}</span><span>${escapeHtml(entry.label)}</span></button></li>`).join('')}</ol>`;panel.querySelectorAll('[data-history-index]').forEach(button=>button.addEventListener('click',()=>restoreHistoryTo(Number(button.dataset.historyIndex))));}

function updateMoveable(){state.moveable?.destroy();state.moveable=null;const project=activeProject(),layer=activeLayer();if(!project||!layer||state.tool!=='move'||!layerIsVisible(project,layer))return;const canvas=document.getElementById('canvas'),target=canvas.querySelector(`[data-layer-id="${layer.id}"]`);if(!target)return;const otherLayers=[...canvas.querySelectorAll('.ps-canvas-layer')].filter(element=>element!==target&&element.style.display!=='none'),showControls=document.getElementById('transformControls').checked;state.moveable=new Moveable(canvas,{target,draggable:true,resizable:showControls,rotatable:showControls,hideDefaultLines:!showControls,snappable:true,snapThreshold:7,snapGap:true,isDisplaySnapDigit:true,snapDirections:{left:true,right:true,top:true,bottom:true,center:true,middle:true},verticalGuidelines:[0,project.width*state.zoom/2,project.width*state.zoom],horizontalGuidelines:[0,project.height*state.zoom/2,project.height*state.zoom],elementGuidelines:otherLayers,origin:false,keepRatio:true,renderDirections:showControls?['nw','n','ne','w','e','sw','s','se']:[]});state.moveable.on('drag',event=>{target.style.left=`${event.left}px`;target.style.top=`${event.top}px`;}).on('dragEnd',()=>{layer.x=parseFloat(target.style.left)/state.zoom;layer.y=parseFloat(target.style.top)/state.zoom;updateLayer(layer,{x:layer.x,y:layer.y},'Move');}).on('resizeStart',event=>event.setRatio(event.inputEvent?.shiftKey?0:layerOriginalRatio(layer))).on('resize',event=>{target.style.width=`${event.width}px`;target.style.height=`${event.height}px`;target.style.transform=event.drag.transform.replace(/translate\([^)]*\)/,'')+` rotate(${layer.rotation}deg)`;target.style.left=`${event.drag.left}px`;target.style.top=`${event.drag.top}px`;}).on('resizeEnd',()=>{layer.x=parseFloat(target.style.left)/state.zoom;layer.y=parseFloat(target.style.top)/state.zoom;layer.width=parseFloat(target.style.width)/state.zoom;layer.height=parseFloat(target.style.height)/state.zoom;target.style.transform=`rotate(${layer.rotation}deg)`;updateLayer(layer,{x:layer.x,y:layer.y,width:layer.width,height:layer.height},'Transform');}).on('rotate',event=>{target.style.transform=event.transform;}).on('rotateEnd',event=>{layer.rotation=event.lastEvent?.beforeRotate??layer.rotation;updateLayer(layer,{rotation:layer.rotation},'Rotate');});}
async function updateLayer(layer,changes,historyLabel=null){Object.assign(layer,changes);if(historyLabel)recordHistory(historyLabel);else refreshDirty(activeProject());renderProperties();return layer;}
function layerOriginalRatio(layer){const width=Number(layer.original_width||layer.width),height=Number(layer.original_height||layer.height);return width>0&&height>0?width/height:1;}
function restoreActiveLayerAspectRatio(){const layer=activeLayer();if(!layer)return;const ratio=layerOriginalRatio(layer);let width=Number(layer.width),height=Number(layer.height);if(width>=height)height=width/ratio;else width=height*ratio;updateLayer(layer,{width:Number(width.toFixed(3)),height:Number(height.toFixed(3))},'Restore Aspect Ratio').then(render);}
function alignActiveLayers(mode){
    const project=activeProject(),layers=selectedLayers();if(!project||!layers.length)return;
    const horizontal=mode==='hgap',vertical=mode==='vgap';
    if((horizontal||vertical)&&layers.length<3){toast('Select at least three layers to distribute gaps.');return;}
    if(mode==='grid'){layers.forEach(layer=>{layer.x=Math.round(layer.x/10)*10;layer.y=Math.round(layer.y/10)*10;});}
    else if(horizontal||vertical){const axis=horizontal?'x':'y',size=horizontal?'width':'height',ordered=[...layers].sort((a,b)=>a[axis]-b[axis]),start=ordered[0][axis],end=ordered.at(-1)[axis]+ordered.at(-1)[size],total=ordered.reduce((sum,layer)=>sum+layer[size],0),gap=(end-start-total)/(ordered.length-1);let cursor=start;ordered.forEach(layer=>{layer[axis]=cursor;cursor+=layer[size]+gap;});}
    else{const bounds=layers.length===1?{left:0,top:0,right:project.width,bottom:project.height}:{left:Math.min(...layers.map(layer=>layer.x)),top:Math.min(...layers.map(layer=>layer.y)),right:Math.max(...layers.map(layer=>layer.x+layer.width)),bottom:Math.max(...layers.map(layer=>layer.y+layer.height))};layers.forEach(layer=>{if(mode==='left')layer.x=bounds.left;if(mode==='right')layer.x=bounds.right-layer.width;if(mode==='center'||mode==='hcenter')layer.x=(bounds.left+bounds.right-layer.width)/2;if(mode==='top')layer.y=bounds.top;if(mode==='bottom')layer.y=bounds.bottom-layer.height;if(mode==='vcenter')layer.y=(bounds.top+bounds.bottom-layer.height)/2;});}
    recordHistory(mode==='grid'?'Align to Grid':horizontal||vertical?'Distribute Layers':'Align Layers');render();
}

async function addLayer(project,dataUrl,width,height,name,x=0,y=0,historyLabel='New Layer',options={}){const parentId=options.parentId??activeFolder()?.id??activeLayer()?.parentId??null;treeChildren(project,parentId).forEach(node=>node.item.order=Number(node.item.order||0)+1);const layer=newLayer(project,{name,dataUrl,width,height,x,y,parentId,order:0,...options});project.layers.push(layer);normalizeProjectTree(project);selectOnlyLayer(layer.id);recordHistory(historyLabel);render();return layer;}
async function createBlankLayer(){const project=activeProject();if(!project){toast('Open a document first.');return;}const canvas=transparentCanvas(project.width,project.height);await addLayer(project,canvasToDataUrl(canvas),project.width,project.height,`Layer ${project.layers.length+1}`);}
function createLayerFolder(){
    const project=activeProject();if(!project){toast('Open a document first.');return;}project.folders=project.folders||[];
    const selected=project.layers.filter(layer=>state.selectedLayerIds.has(layer.id)),chosen=selected.length?selected:(activeLayer()?[activeLayer()]:[]),sameParent=chosen.length&&chosen.every(layer=>treeItemParent(layer)===treeItemParent(chosen[0])),parentId=chosen.length?(sameParent?treeItemParent(chosen[0]):null):(activeFolder()?.id||null),siblings=treeChildren(project,parentId),chosenIds=new Set(chosen.map(layer=>layer.id));let insertAt=chosen.length?Math.min(...siblings.map((node,index)=>node.kind==='layer'&&chosenIds.has(node.item.id)?index:Infinity)):0;if(!Number.isFinite(insertAt))insertAt=0;
    const folder={id:nextFolderId(),name:`Group ${project.folders.length+1}`,parentId,order:insertAt,visible:true,expanded:true,opacity:100,blendMode:'pass through'},remaining=siblings.filter(node=>!(node.kind==='layer'&&chosenIds.has(node.item.id)));remaining.splice(Math.min(insertAt,remaining.length),0,{kind:'folder',item:folder});remaining.forEach((node,order)=>node.item.order=order);project.folders.push(folder);chosen.sort((a,b)=>b.z_index-a.z_index).forEach((layer,order)=>{layer.parentId=folder.id;layer.order=order;});
    normalizeProjectTree(project);selectOnlyFolder(folder.id);switchPanel('layers');recordHistory('New Group');render();toast(chosen.length?`Grouped ${chosen.length} layer${chosen.length===1?'':'s'} in ${folder.name}.`:`Created ${folder.name}.`);
}function deletionSelection(project){
    const folderIds=new Set(state.selectedFolderIds),layerIds=new Set(state.selectedLayerIds);if(!folderIds.size&&!layerIds.size){if(activeFolder())folderIds.add(activeFolder().id);else if(activeLayer())layerIds.add(activeLayer().id);}let changed=true;while(changed){changed=false;for(const folder of project.folders||[])if(folder.parentId&&folderIds.has(folder.parentId)&&!folderIds.has(folder.id)){folderIds.add(folder.id);changed=true;}}for(const layer of project.layers)if(folderAncestors(project,layer.parentId).some(folder=>folderIds.has(folder.id)))layerIds.add(layer.id);return {folderIds,layerIds};
}
function requestDeleteSelected(){const project=activeProject();if(!project)return;const {folderIds,layerIds}=deletionSelection(project);if(!folderIds.size&&!layerIds.size){toast('Select a layer or group to delete.');return;}const groups=folderIds.size,layers=layerIds.size,message=document.getElementById('deleteLayersMessage');message.textContent=groups?`Delete ${groups} group${groups===1?'':'s'} and ${layers} contained layer${layers===1?'':'s'}?`:`Delete ${layers} selected layer${layers===1?'':'s'}?`;document.getElementById('deleteLayersDialog').showModal();}
function deleteSelectedItems(){
    const project=activeProject();if(!project)return;const {folderIds,layerIds}=deletionSelection(project);if(!folderIds.size&&!layerIds.size)return;for(const id of layerIds)for(const role of ['canvas','layers','properties']){const key=`${role}:${id}`;state.imageElements.delete(key);state.imageSources.delete(key);}project.layers=project.layers.filter(layer=>!layerIds.has(layer.id));project.folders=(project.folders||[]).filter(folder=>!folderIds.has(folder.id));normalizeProjectTree(project);selectOnlyLayer(topLayer(project)?.id||null);document.getElementById('deleteLayersDialog').close();recordHistory(folderIds.size?'Delete Group':'Delete Layer');render();toast(`Deleted ${layerIds.size} layer${layerIds.size===1?'':'s'}${folderIds.size?` in ${folderIds.size} group${folderIds.size===1?'':'s'}`:''}.`);
}
async function duplicateLayer(){const project=activeProject(),layer=activeLayer();if(!project||!layer){toast('Select a layer first.');return;}await addLayer(project,layer.image_url,layer.width,layer.height,`${layer.name} copy`,layer.x+10,layer.y+10,'Duplicate Layer',{type:layer.type,text:layer.text,textData:layer.textData,blendMode:layer.blendMode,parentId:layer.parentId});}
function renameLayer(){const item=activeLayer()||activeFolder();if(!item)return;const name=prompt(activeFolder()?'Group name':'Layer name',item.name);if(name?.trim()){item.name=name.trim();recordHistory(activeFolder()?'Rename Group':'Rename Layer');render();}}
function makeTextCanvas(text,fontSize=36,color='#000'){const lines=String(text).split(/\r?\n/),probe=transparentCanvas(1,1),probeContext=probe.getContext('2d');probeContext.font=`${fontSize}px Arial`;const width=Math.max(2,Math.ceil(Math.max(...lines.map(line=>probeContext.measureText(line||' ').width))+8)),lineHeight=Math.ceil(fontSize*1.25),canvas=transparentCanvas(width,lineHeight*lines.length+6),context=canvas.getContext('2d');context.font=`${fontSize}px Arial`;context.textBaseline='top';context.fillStyle=color;lines.forEach((line,index)=>context.fillText(line,4,3+index*lineHeight));return canvas;}
async function addTextLayerAt(x,y){const project=activeProject();if(!project){toast('Open a document first.');return;}const text=prompt('Text for the new layer','Text');if(!text)return;const fontSize=36,canvas=makeTextCanvas(text,fontSize);const textData={text,transform:[1,0,0,1,x,y+fontSize],style:{font:{name:'ArialMT'},fontSize,fillColor:{r:0,g:0,b:0}}};await addLayer(project,canvasToDataUrl(canvas),canvas.width,canvas.height,text.slice(0,40),x,y,'New Text Layer',{type:'text',text,textData});}
function addTextLayerAtCenter(){const project=activeProject();if(project)addTextLayerAt(Math.max(0,(project.width-200)/2),Math.max(0,(project.height-50)/2));}

function selectArea(area){if(!activeProject())return;state.selection=area;renderSelection();}
function clearSelection(){state.selection=null;renderSelection();}
function renderSelection(){const box=document.getElementById('selectionBox');if(!state.selection||!activeProject()){box.hidden=true;return;}box.hidden=false;Object.assign(box.style,{left:`${state.selection.x*state.zoom}px`,top:`${state.selection.y*state.zoom}px`,width:`${state.selection.width*state.zoom}px`,height:`${state.selection.height*state.zoom}px`});}
async function copySelection(){const project=activeProject();if(!project)return;const area=state.selection||{x:0,y:0,width:project.width,height:project.height},composite=await renderComposite(project),out=transparentCanvas(Math.round(area.width),Math.round(area.height));out.getContext('2d').drawImage(composite,area.x,area.y,area.width,area.height,0,0,out.width,out.height);state.clipboard={dataUrl:canvasToDataUrl(out),width:out.width,height:out.height,x:area.x,y:area.y};try{const blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));await navigator.clipboard?.write([new ClipboardItem({'image/png':blob})]);}catch{}toast(`Copied ${out.width} × ${out.height}px.`);}
async function pasteClipboard(inPlace=false){const project=activeProject();if(!project)return;let clip=state.clipboard;if(!clip){try{const item=(await navigator.clipboard.read()).find(entry=>entry.types.includes('image/png'));if(item){const png=await imageFileToPng(await item.getType('image/png'));clip={...png,x:0,y:0};}}catch{}}if(!clip){toast('Nothing copied yet.');return;}const x=inPlace?clip.x:(project.width-clip.width)/2,y=inPlace?clip.y:(project.height-clip.height)/2;await addLayer(project,clip.dataUrl,clip.width,clip.height,`Pasted layer ${project.layers.length+1}`,x,y,'Paste');}

function releaseProjectImageCache(project){for(const layer of project?.layers||[])for(const role of ['canvas','layers','properties']){const key=`${role}:${layer.id}`;state.imageElements.delete(key);state.imageSources.delete(key);}state.thumbnailCache.clear();}
function closeTab(id){if(!id)return;if(state.dirtyProjects.has(id)&&!confirm('Close this document without downloading its latest PSD?'))return;const project=state.projects.get(id),index=state.tabs.indexOf(id),wasActive=state.activeProjectId===id;releaseProjectImageCache(project);state.tabs=state.tabs.filter(tab=>tab!==id);state.projects.delete(id);state.zooms.delete(id);state.histories.delete(id);state.savedSignatures.delete(id);state.dirtyProjects.delete(id);if(wasActive)state.activeProjectId=state.tabs[Math.max(0,index-1)]||state.tabs[0]||null;state.zoom=state.activeProjectId?(state.zooms.get(state.activeProjectId)||1):1;selectOnlyLayer(topLayer(activeProject())?.id||null);clearSelection();render();}
function setZoom(value){state.zoom=Math.min(4,Math.max(.05,value));if(state.activeProjectId)state.zooms.set(state.activeProjectId,state.zoom);renderCanvas();renderTabs();}
function fitScreen(){const project=activeProject(),viewport=document.getElementById('stageViewport');if(project)setZoom(Math.min(1,(viewport.clientWidth-100)/project.width,(viewport.clientHeight-150)/project.height));}

let imageSizeRatio=1;
let canvasAnchor='center';
function updateImageSizeReadout(){const width=Math.max(1,Math.round(Number(document.getElementById('imageSizeWidth').value)||1)),height=Math.max(1,Math.round(Number(document.getElementById('imageSizeHeight').value)||1));document.getElementById('imageSizeDimensions').textContent=`${width} px × ${height} px`;document.getElementById('imageSizeSummary').textContent=`Image Size: ${(width*height/1000000).toFixed(2)} MP`;}
async function updateImageSizePreview(project){const image=document.getElementById('imageSizePreview');image.removeAttribute('src');try{const composite=await renderComposite(project),scale=Math.min(1,230/project.width,290/project.height),preview=transparentCanvas(Math.max(1,Math.round(project.width*scale)),Math.max(1,Math.round(project.height*scale)));preview.getContext('2d').drawImage(composite,0,0,preview.width,preview.height);if(activeProject()?.id===project.id)image.src=canvasToDataUrl(preview);}catch{}}
function openImageSizeDialog(){const project=activeProject();if(!project){toast('Open a document first.');return;}imageSizeRatio=project.width/project.height;document.getElementById('imageSizeWidth').value=project.width;document.getElementById('imageSizeHeight').value=project.height;document.getElementById('imageSizeLock').checked=true;updateImageSizeReadout();document.getElementById('imageSizeDialog').showModal();updateImageSizePreview(project);}
function scaleTextLayerData(layer,scaleX,scaleY){if(!layer.textData)return;const text=clonePlain(layer.textData),transform=Array.isArray(text.transform)&&text.transform.length>=6?[...text.transform]:null;if(transform){transform[0]*=scaleX;transform[2]*=scaleX;transform[4]*=scaleX;transform[1]*=scaleY;transform[3]*=scaleY;transform[5]*=scaleY;text.transform=transform;}layer.textData=text;}
function applyImageSize(width,height){const project=activeProject();if(!project)return;const nextWidth=Math.round(Number(width)),nextHeight=Math.round(Number(height));if(nextWidth<1||nextHeight<1||nextWidth>8192||nextHeight>8192){toast('Image dimensions must be between 1 and 8,192 pixels.');return;}const scaleX=nextWidth/project.width,scaleY=nextHeight/project.height;project.layers.forEach(layer=>{layer.x*=scaleX;layer.y*=scaleY;layer.width*=scaleX;layer.height*=scaleY;layer.text_origin_x*=scaleX;layer.text_origin_y*=scaleY;scaleTextLayerData(layer,scaleX,scaleY);});if(state.selection)state.selection={x:state.selection.x*scaleX,y:state.selection.y*scaleY,width:state.selection.width*scaleX,height:state.selection.height*scaleY};project.width=nextWidth;project.height=nextHeight;document.getElementById('imageSizeDialog').close();recordHistory('Image Size');render();requestAnimationFrame(fitScreen);}
function setCanvasAnchor(anchor){canvasAnchor=anchor;document.querySelectorAll('[data-canvas-anchor]').forEach(button=>button.classList.toggle('active',button.dataset.canvasAnchor===anchor));}
function openCanvasSizeDialog(){const project=activeProject();if(!project){toast('Open a document first.');return;}document.getElementById('canvasCurrentWidth').textContent=project.width;document.getElementById('canvasCurrentHeight').textContent=project.height;document.getElementById('canvasSizeWidth').value=project.width;document.getElementById('canvasSizeHeight').value=project.height;document.getElementById('canvasSizeRelative').checked=false;setCanvasAnchor('center');document.getElementById('canvasSizeDialog').showModal();}
function applyCanvasSize(width,height,relative=false){const project=activeProject();if(!project)return;const requestedWidth=Math.round(Number(width)),requestedHeight=Math.round(Number(height)),nextWidth=relative?project.width+requestedWidth:requestedWidth,nextHeight=relative?project.height+requestedHeight:requestedHeight;if(nextWidth<1||nextHeight<1||nextWidth>8192||nextHeight>8192){toast('Canvas dimensions must be between 1 and 8,192 pixels.');return;}const anchors={topLeft:[0,0],top:[.5,0],topRight:[1,0],left:[0,.5],center:[.5,.5],right:[1,.5],bottomLeft:[0,1],bottom:[.5,1],bottomRight:[1,1]},key=canvasAnchor.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase()),[anchorX,anchorY]=anchors[key]||anchors.center,offsetX=(nextWidth-project.width)*anchorX,offsetY=(nextHeight-project.height)*anchorY;project.layers.forEach(layer=>{layer.x+=offsetX;layer.y+=offsetY;layer.text_origin_x+=offsetX;layer.text_origin_y+=offsetY;if(layer.textData&&Array.isArray(layer.textData.transform)&&layer.textData.transform.length>=6){layer.textData=clonePlain(layer.textData);layer.textData.transform[4]+=offsetX;layer.textData.transform[5]+=offsetY;}});if(state.selection)state.selection={...state.selection,x:state.selection.x+offsetX,y:state.selection.y+offsetY};project.width=nextWidth;project.height=nextHeight;document.getElementById('canvasSizeDialog').close();recordHistory('Canvas Size');render();requestAnimationFrame(fitScreen);}
async function buildMenus(){const menus=await fetch('/photoshop-menus.json').then(response=>response.json()),bar=document.getElementById('menuBar');menus.filter(menu=>menu.visible).forEach(menu=>{const wrap=document.createElement('div');wrap.className='ps-menu';const button=document.createElement('button');button.className='ps-menu-button';button.textContent=menu.label;button.type='button';const panel=document.createElement('div');panel.className='ps-menu-panel';panel.hidden=true;menu.items.filter(item=>item.visible).forEach(item=>panel.append(buildMenuItem(item)));button.addEventListener('click',event=>{event.stopPropagation();const opening=panel.hidden;closeMenus();panel.hidden=!opening;wrap.classList.toggle('open',opening);});wrap.append(button,panel);bar.append(wrap);});}
function buildMenuItem(item){if(item.separator){const line=document.createElement('div');line.className='ps-menu-separator';return line;}const button=document.createElement('button');button.type='button';button.className='ps-menu-item';button.disabled=item.enabled===false;const label=document.createElement('span');label.textContent=item.label;const suffix=document.createElement('span');suffix.className='ps-menu-shortcut';if(item.children)suffix.innerHTML=iconMarkup('lrs-arrow_right');else suffix.textContent=item.shortcut||'';button.append(label,suffix);if(item.children){const sub=document.createElement('span');sub.className='ps-submenu';item.children.filter(child=>child.visible).forEach(child=>sub.append(buildMenuItem(child)));button.append(sub);}if(item.action)button.addEventListener('click',event=>{event.stopPropagation();closeMenus();actions[item.action]?.();});return button;}
function closeMenus(){document.querySelectorAll('.ps-menu-panel').forEach(panel=>panel.hidden=true);document.querySelectorAll('.ps-menu').forEach(menu=>menu.classList.remove('open'));}
function toolMeta(id){for(const group of toolGroups){const tool=group.tools.find(item=>item.id===id);if(tool)return {...tool,group};}return null;}
function closeToolFlyouts(except=null){document.querySelectorAll('.ps-tool-group.open').forEach(group=>{if(group!==except)group.classList.remove('open');});}
function buildTools(){const panel=document.getElementById('toolsPanel');toolGroups.forEach(group=>{group.activeId=group.tools[0].id;const wrapper=document.createElement('div');wrapper.className=`ps-tool-group${group.id==='move'?' active':''}`;wrapper.dataset.toolGroup=group.id;const main=document.createElement('button');main.type='button';main.className='ps-tool';main.dataset.tool=group.activeId;main.title=group.tools[0].name;main.innerHTML=`${iconMarkup(group.tools[0].icon,'ps-tool-icon')}<kbd>${group.key}</kbd>`;wrapper.append(main);if(group.tools.length>1){const toggle=document.createElement('button');toggle.type='button';toggle.className='ps-tool-flyout-toggle';toggle.innerHTML=iconMarkup('lrs-arrow_right','ps-tool-flyout-arrow');const flyout=document.createElement('div');flyout.className='ps-tool-flyout';group.tools.forEach(tool=>{const item=document.createElement('button');item.type='button';item.className='ps-tool-flyout-item';item.dataset.tool=tool.id;item.innerHTML=`${iconMarkup(tool.icon,'ps-tool-icon')}<span>${escapeHtml(tool.name)}</span><kbd>${group.key}</kbd>`;flyout.append(item);});toggle.addEventListener('click',event=>{event.stopPropagation();const opening=!wrapper.classList.contains('open');closeToolFlyouts();wrapper.classList.toggle('open',opening);});wrapper.addEventListener('contextmenu',event=>{event.preventDefault();closeToolFlyouts();wrapper.classList.add('open');});wrapper.append(toggle,flyout);}panel.append(wrapper);});}
function selectTool(tool){const meta=toolMeta(tool);if(!meta)return;meta.group.activeId=tool;state.tool=tool;document.querySelectorAll('.ps-tool-group').forEach(wrapper=>wrapper.classList.toggle('active',wrapper.dataset.toolGroup===meta.group.id));const groupButton=document.querySelector(`[data-tool-group="${meta.group.id}"] > .ps-tool`);if(groupButton){groupButton.dataset.tool=tool;groupButton.title=meta.name;groupButton.innerHTML=`${iconMarkup(meta.icon,'ps-tool-icon')}<kbd>${meta.group.key}</kbd>`;}document.getElementById('activeToolIcon').innerHTML=iconMarkup(meta.icon);document.getElementById('activeToolName').textContent=meta.name;closeToolFlyouts();if(!['move','marquee','zoom','zoom-in','zoom-out','horizontal-type'].includes(tool))toast(`${meta.name} will be added in a later version.`);updateMoveable();}

function renderTemplateCategories(){const nav=document.getElementById('templateCategories');nav.replaceChildren(...documentTemplateCategories.map(category=>{const button=document.createElement('button');button.type='button';button.textContent=category.label;button.classList.toggle('active',category.id===activeTemplateCategory);button.addEventListener('click',()=>{activeTemplateCategory=category.id;selectedDocumentTemplateId=null;renderTemplateCategories();renderTemplateGrid();});return button;}));}
function renderTemplateGrid(){const grid=document.getElementById('templateGrid'),category=documentTemplateCategories.find(item=>item.id===activeTemplateCategory);grid.replaceChildren(...(category?.templates||[]).map(template=>{const card=document.createElement('button');card.type='button';card.className='ps-template-card';card.classList.toggle('selected',template.id===selectedDocumentTemplateId);const scale=Math.min(166/Number(template.width),106/Number(template.height)),preview=document.createElement('span');preview.className='ps-template-preview';preview.style.width=`${Math.max(2,Number(template.width)*scale)}px`;preview.style.height=`${Math.max(2,Number(template.height)*scale)}px`;const title=document.createElement('strong');title.textContent=template.title||'';title.hidden=!template.title;const dimensions=document.createElement('span');dimensions.className='ps-template-dimensions';dimensions.textContent=template.display;card.append(preview,title,dimensions);card.addEventListener('click',()=>selectDocumentTemplate(template));return card;}));}
function selectDocumentTemplate(template){selectedDocumentTemplateId=template.id;document.getElementById('projectWidth').value=template.width;document.getElementById('projectHeight').value=template.height;document.getElementById('documentUnit').value=template.unit;document.getElementById('documentDpi').value=template.dpi;renderTemplateGrid();}
function documentPixelDimensions(){const width=Number(document.getElementById('projectWidth').value),height=Number(document.getElementById('projectHeight').value),dpi=Number(document.getElementById('documentDpi').value),unit=document.getElementById('documentUnit').value,multiplier=unit==='in'?dpi:unit==='mm'?dpi/25.4:1;return {width:Math.round(width*multiplier),height:Math.round(height*multiplier)};}
async function loadDocumentTemplates(){const response=await fetch('/photoshop-templates.json');if(!response.ok)throw new Error('Could not load document templates.');documentTemplateCategories=(await response.json()).categories||[];activeTemplateCategory=documentTemplateCategories[0]?.id||'social';renderTemplateCategories();renderTemplateGrid();}

document.addEventListener('click',event=>{if(!event.target.closest('.ps-menu'))closeMenus();if(!event.target.closest('.ps-tool-group'))closeToolFlyouts();if(!event.target.closest('#opacityControl'))document.getElementById('opacityPopover').hidden=true;const action=event.target.closest('[data-action]')?.dataset.action;if(action)actions[action]?.();const tool=event.target.closest('[data-tool]')?.dataset.tool;if(tool)selectTool(tool);const panel=event.target.closest('[data-panel-tab]')?.dataset.panelTab;if(panel)switchPanel(panel);const align=event.target.closest('[data-align-layer]')?.dataset.alignLayer;if(align)alignActiveLayers(align);});
document.addEventListener('keydown',event=>{const mod=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if(mod&&key==='z'){event.preventDefault();event.shiftKey?actions.redo():actions.undo();return;}if(mod&&key==='y'){event.preventDefault();actions.redo();return;}if(mod&&key==='s'){event.preventDefault();exportActiveProjectAsPsd();return;}if(mod&&(key==='+'||key==='=')){event.preventDefault();actions.zoomIn();return;}if(mod&&key==='-'){event.preventDefault();actions.zoomOut();return;}if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;let action=null;if(mod&&key==='n')action='newProject';if(mod&&key==='o')action='openLocal';if(mod&&key==='a')action='selectAll';if(mod&&key==='c')action='copy';if(mod&&key==='v')action='paste';if(mod&&key==='d')action='deselect';if(mod&&event.key==='0')action='fitScreen';if(mod&&event.key==='1')action='actualPixels';if(action){event.preventDefault();actions[action]?.();}if(!mod&&['v','m','t','z'].includes(key))selectTool(key==='m'?'marquee':key==='v'?'move':key==='t'?'horizontal-type':'zoom');if(!mod&&event.key==='Delete'){event.preventDefault();actions.deleteLayers();}});
document.getElementById('newProjectForm').addEventListener('submit',event=>{event.preventDefault();if(event.submitter?.value==='cancel'){document.getElementById('newProjectDialog').close();return;}const dimensions=documentPixelDimensions();if(dimensions.width<1||dimensions.height<1||dimensions.width>8192||dimensions.height>8192){toast('Document dimensions must resolve to between 1 and 8,192 pixels.');return;}const project={id:nextProjectId(),name:document.getElementById('newProjectName').value,width:dimensions.width,height:dimensions.height,layers:[]},canvas=transparentCanvas(dimensions.width,dimensions.height);project.layers.push(newLayer(project,{name:'Layer 1',dataUrl:canvasToDataUrl(canvas),width:dimensions.width,height:dimensions.height,z_index:0}));createLocalProject({...project,historyLabel:'New',clean:false});document.getElementById('newProjectDialog').close();});
document.getElementById('swapDimensions').addEventListener('click',()=>{const width=document.getElementById('projectWidth'),height=document.getElementById('projectHeight'),next=width.value;width.value=height.value;height.value=next;selectedDocumentTemplateId=null;renderTemplateGrid();});
for(const id of ['projectWidth','projectHeight','documentUnit','documentDpi'])document.getElementById(id).addEventListener('input',()=>{selectedDocumentTemplateId=null;renderTemplateGrid();});
document.getElementById('localFileInput').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{await openLocalFile(file);}catch(error){toast(error.message||'Could not open that local file.');}});
document.getElementById('placeImageInput').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{await placeLocalImage(file);}catch(error){toast(error.message||'Could not place that image.');}});
const imageSizeWidth=document.getElementById('imageSizeWidth'),imageSizeHeight=document.getElementById('imageSizeHeight'),imageSizeLock=document.getElementById('imageSizeLock');
imageSizeWidth.addEventListener('input',()=>{if(imageSizeLock.checked)imageSizeHeight.value=Math.max(1,Math.round((Number(imageSizeWidth.value)||1)/imageSizeRatio));updateImageSizeReadout();});
imageSizeHeight.addEventListener('input',()=>{if(imageSizeLock.checked)imageSizeWidth.value=Math.max(1,Math.round((Number(imageSizeHeight.value)||1)*imageSizeRatio));updateImageSizeReadout();});
document.getElementById('imageSizeForm').addEventListener('submit',event=>{event.preventDefault();if(event.submitter?.value==='confirm')applyImageSize(imageSizeWidth.value,imageSizeHeight.value);else document.getElementById('imageSizeDialog').close();});
document.querySelectorAll('[data-canvas-anchor]').forEach(button=>button.addEventListener('click',()=>setCanvasAnchor(button.dataset.canvasAnchor)));
document.getElementById('canvasSizeRelative').addEventListener('change',event=>{const project=activeProject();if(!project)return;document.getElementById('canvasSizeWidth').value=event.target.checked?0:project.width;document.getElementById('canvasSizeHeight').value=event.target.checked?0:project.height;});
document.getElementById('canvasSizeForm').addEventListener('submit',event=>{event.preventDefault();if(event.submitter?.value==='confirm')applyCanvasSize(document.getElementById('canvasSizeWidth').value,document.getElementById('canvasSizeHeight').value,document.getElementById('canvasSizeRelative').checked);else document.getElementById('canvasSizeDialog').close();});
document.querySelector('[data-close-layerize-history]').addEventListener('click',()=>document.getElementById('layerizeHistoryDialog').close());
document.getElementById('deleteLayersForm').addEventListener('submit',event=>{event.preventDefault();if(event.submitter?.value==='delete')deleteSelectedItems();else document.getElementById('deleteLayersDialog').close();});
const opacityInput=document.getElementById('layerOpacity'),opacitySlider=document.getElementById('layerOpacitySlider'),opacityPopover=document.getElementById('opacityPopover');
function showOpacitySlider(){if(activeLayer())opacityPopover.hidden=false;}
document.getElementById('opacityTrigger').addEventListener('click',()=>{if(activeLayer())opacityPopover.hidden=!opacityPopover.hidden;});
opacityInput.addEventListener('click',showOpacitySlider);
opacityInput.addEventListener('change',event=>{const layer=activeLayer();if(!layer)return;const value=Math.max(0,Math.min(100,Number(event.target.value)||0));event.target.value=value;opacitySlider.value=value;updateLayer(layer,{opacity:value},'Opacity Change').then(renderCanvas);});
opacitySlider.addEventListener('focus',()=>{const layer=activeLayer();if(layer)opacitySlider.dataset.start=String(layer.opacity);});
opacitySlider.addEventListener('pointerdown',()=>{const layer=activeLayer();if(layer)opacitySlider.dataset.start=String(layer.opacity);});
opacitySlider.addEventListener('input',event=>{const layer=activeLayer();if(!layer)return;layer.opacity=Number(event.target.value);opacityInput.value=event.target.value;refreshDirty(activeProject());renderCanvas();renderProperties();});
opacitySlider.addEventListener('change',()=>{const layer=activeLayer();if(layer&&Number(opacitySlider.dataset.start)!==layer.opacity)recordHistory('Opacity Change');});
document.getElementById('layerBlendMode').addEventListener('change',event=>{const layer=activeLayer();if(layer)updateLayer(layer,{blendMode:event.target.value},'Blending Change').then(renderCanvas);});
document.getElementById('transformControls').addEventListener('change',updateMoveable);
document.getElementById('propertiesPanel').addEventListener('change',event=>{const input=event.target.closest('[data-layer-property]'),layer=activeLayer();if(!input||!layer)return;const property=input.dataset.layerProperty,value=Number(input.value);if(Number.isFinite(value))updateLayer(layer,{[property]:value},property==='opacity'?'Opacity Change':'Transform').then(render);});
document.getElementById('canvas').addEventListener('pointerdown',event=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),point={x:(event.clientX-rect.left)/state.zoom,y:(event.clientY-rect.top)/state.zoom};if(state.tool==='horizontal-type'){addTextLayerAt(point.x,point.y);return;}if(['zoom','zoom-in','zoom-out'].includes(state.tool)){const zoomOut=state.tool==='zoom-out'||(state.tool==='zoom'&&event.altKey);setZoom(state.zoom*(zoomOut ? .8 : 1.25));return;}if(state.tool!=='marquee')return;const start=point;canvas.setPointerCapture(event.pointerId);const move=next=>{const x=(next.clientX-rect.left)/state.zoom,y=(next.clientY-rect.top)/state.zoom;selectArea({x:Math.max(0,Math.min(start.x,x)),y:Math.max(0,Math.min(start.y,y)),width:Math.min(activeProject().width,Math.abs(x-start.x)),height:Math.min(activeProject().height,Math.abs(y-start.y))});};const up=()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);});
window.addEventListener('resize',()=>{if(activeProject())fitScreen();});

async function init(){buildTools();updateSaveUi();try{await Promise.all([buildMenus(),loadDocumentTemplates()]);}catch(error){toast(error.message);}}
init();
